//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.HelpDeskPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.HelpDeskPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , by.
        /// </summary>
        public static string _by {
            get {
                return ResourceManager.GetString("_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close ticket.
        /// </summary>
        public static string Close_job {
            get {
                return ResourceManager.GetString("Close_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort.
        /// </summary>
        public static string Effort {
            get {
                return ResourceManager.GetString("Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Help_desk {
            get {
                return ResourceManager.GetString("Help_desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string hrs {
            get {
                return ResourceManager.GetString("hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} opened tickets(s).
        /// </summary>
        public static string N_open_jobs {
            get {
                return ResourceManager.GetString("N_open_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ticket.
        /// </summary>
        public static string New_ticket {
            get {
                return ResourceManager.GetString("New_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket description.
        /// </summary>
        public static string New_ticket_name {
            get {
                return ResourceManager.GetString("New_ticket_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only projects i&apos;m envolved.
        /// </summary>
        public static string only_projects_im_envolved {
            get {
                return ResourceManager.GetString("only_projects_im_envolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press Esc to cancel.
        /// </summary>
        public static string press_Esc_to_cancel {
            get {
                return ResourceManager.GetString("press_Esc_to_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task.
        /// </summary>
        public static string work_on_it {
            get {
                return ResourceManager.GetString("work_on_it", resourceCulture);
            }
        }
    }
}
