//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Backlog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.Backlog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sprint.
        /// </summary>
        public static string Add_sprint {
            get {
                return ResourceManager.GetString("Add_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ALL_BACKLOG {
            get {
                return ResourceManager.GetString("ALL_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items.
        /// </summary>
        public static string ALL_BACKLOG_tooltip {
            get {
                return ResourceManager.GetString("ALL_BACKLOG_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any date.
        /// </summary>
        public static string any_date {
            get {
                return ResourceManager.GetString("any_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the &apos;{0}&apos; backlog item?.
        /// </summary>
        public static string Are_you_sure_remove_item {
            get {
                return ResourceManager.GetString("Are_you_sure_remove_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at this date.
        /// </summary>
        public static string at_this_date {
            get {
                return ResourceManager.GetString("at_this_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog.
        /// </summary>
        public static string Backlog {
            get {
                return ResourceManager.GetString("Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog item.
        /// </summary>
        public static string Backlog_item {
            get {
                return ResourceManager.GetString("Backlog_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog Item {0}.
        /// </summary>
        public static string Backlog_Item_0 {
            get {
                return ResourceManager.GetString("Backlog_Item_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove a backlog item that has been already planned..
        /// </summary>
        public static string BRE_CAN_DELETE_ALREADY_PLANNED_ITEM_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ALREADY_PLANNED_ITEM_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the Backlog item.
        /// </summary>
        public static string BRE_CAN_DELETE_ALREADY_PLANNED_ITEM_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ALREADY_PLANNED_ITEM_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items at proposals can not be removed from the backlog..
        /// </summary>
        public static string BRE_CAN_DELETE_ITEM_AT_PROPOSAL_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ITEM_AT_PROPOSAL_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the Backlog item.
        /// </summary>
        public static string BRE_CAN_DELETE_ITEM_AT_PROPOSAL_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ITEM_AT_PROPOSAL_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog items with assigned tasks can not be removed..
        /// </summary>
        public static string BRE_CAN_DELETE_ITEM_WITH_TASKS_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ITEM_WITH_TASKS_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the Backlog item.
        /// </summary>
        public static string BRE_CAN_DELETE_ITEM_WITH_TASKS_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ITEM_WITH_TASKS_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change the sprint end date.
        ///It should be a date after the sprint start date..
        /// </summary>
        public static string BRE_END_DATE_NOT_ALLOWED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_END_DATE_NOT_ALLOWED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove a item size that has been already used at a project.
        ///You still can disable it..
        /// </summary>
        public static string BRE_ITEM_SIZE_ALREADY_USED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_ITEM_SIZE_ALREADY_USED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove item size.
        /// </summary>
        public static string BRE_ITEM_SIZE_ALREADY_USED_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_ITEM_SIZE_ALREADY_USED_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default Plan and Delivery item sizes can not be deleted..
        /// </summary>
        public static string BRE_PLAN_ITEM_SIZE_CAN_NOT_BE_DELETED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_PLAN_ITEM_SIZE_CAN_NOT_BE_DELETED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove item size.
        /// </summary>
        public static string BRE_PLAN_ITEM_SIZE_CAN_NOT_BE_DELETED_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_PLAN_ITEM_SIZE_CAN_NOT_BE_DELETED_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change the sprint start date.
        ///It should be a date after the previuos sprint start date..
        /// </summary>
        public static string BRE_SPRINT_START_DATE_NOT_ALLOWED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_SPRINT_START_DATE_NOT_ALLOWED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint date change not allowed.
        /// </summary>
        public static string BRE_SPRINT_START_DATE_NOT_ALLOWED_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_SPRINT_START_DATE_NOT_ALLOWED_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with current planning.
        /// </summary>
        public static string C_tooltip {
            get {
                return ResourceManager.GetString("C_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculating....
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item was planned at sprint {0} that is now over.
        ///If you want to change the planned hours to the current sprint click at the re-plan button.
        ///If the item is finished change the item status..
        /// </summary>
        public static string Can_not_change_item_hours {
            get {
                return ResourceManager.GetString("Can_not_change_item_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to change item planned hours.
        /// </summary>
        public static string Can_not_change_item_hours_Title {
            get {
                return ResourceManager.GetString("Can_not_change_item_hours_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change it.
        /// </summary>
        public static string Change_it {
            get {
                return ResourceManager.GetString("Change_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change log.
        /// </summary>
        public static string Change_log {
            get {
                return ResourceManager.GetString("Change_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to see suggested hours.
        /// </summary>
        public static string click_here_to_see_suggested_hours {
            get {
                return ResourceManager.GetString("click_here_to_see_suggested_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl-C to copy.
        /// </summary>
        public static string copyitems_tooltip {
            get {
                return ResourceManager.GetString("copyitems_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not paste items.
        /// </summary>
        public static string Could_not_paste_items {
            get {
                return ResourceManager.GetString("Could_not_paste_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not suggest hours.
        /// </summary>
        public static string Could_not_suggest_hours {
            get {
                return ResourceManager.GetString("Could_not_suggest_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string current_sprint {
            get {
                return ResourceManager.GetString("current_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MMM.
        /// </summary>
        public static string dd_MMM {
            get {
                return ResourceManager.GetString("dd_MMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease business priority.
        /// </summary>
        public static string Decrease_business_priority {
            get {
                return ResourceManager.GetString("Decrease_business_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery this item at.
        /// </summary>
        public static string Delivery_at {
            get {
                return ResourceManager.GetString("Delivery_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery this item at the end of the sprint.
        /// </summary>
        public static string Delivery_at_the_end_of_the_sprint {
            get {
                return ResourceManager.GetString("Delivery_at_the_end_of_the_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliveries.
        /// </summary>
        public static string DELIVERY_GROUP {
            get {
                return ResourceManager.GetString("DELIVERY_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This size is uesed for all delivery tasls of each sprint.
        /// </summary>
        public static string Delivery_item_tooltip {
            get {
                return ResourceManager.GetString("Delivery_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed at the sprint end.
        /// </summary>
        public static string DELIVERY_OCC {
            get {
                return ResourceManager.GetString("DELIVERY_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery report.
        /// </summary>
        public static string Delivery_report {
            get {
                return ResourceManager.GetString("Delivery_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery sprint {0}.
        /// </summary>
        public static string Delivery_sprint_N {
            get {
                return ResourceManager.GetString("Delivery_sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (delivery).
        /// </summary>
        public static string deliveryGroup {
            get {
                return ResourceManager.GetString("deliveryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a &lt;user type&gt; I want to &lt;do some action&gt; so that &lt;desired result&gt;.
        /// </summary>
        public static string Description_tooltip {
            get {
                return ResourceManager.GetString("Description_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string DEV_GROUP {
            get {
                return ResourceManager.GetString("DEV_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Along the sprint.
        /// </summary>
        public static string DEVELOPMENT_OCC {
            get {
                return ResourceManager.GetString("DEVELOPMENT_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop items here.
        /// </summary>
        public static string Drop_items_here {
            get {
                return ResourceManager.GetString("Drop_items_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to.
        /// </summary>
        public static string Due_to {
            get {
                return ResourceManager.GetString("Due_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string End_date {
            get {
                return ResourceManager.GetString("End_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end of sprint.
        /// </summary>
        public static string end_of_the_sprint {
            get {
                return ResourceManager.GetString("end_of_the_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end of sprint {0}.
        /// </summary>
        public static string end_of_the_sprint_N {
            get {
                return ResourceManager.GetString("end_of_the_sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backlog items will be equality distributed between the remaining sprints.
        ///Confirm?.
        /// </summary>
        public static string Equalise_tooltip {
            get {
                return ResourceManager.GetString("Equalise_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalize.
        /// </summary>
        public static string Equalize {
            get {
                return ResourceManager.GetString("Equalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1o.
        /// </summary>
        public static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with first planning.
        /// </summary>
        public static string F_tooltip {
            get {
                return ResourceManager.GetString("F_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finished at.
        /// </summary>
        public static string finished_at {
            get {
                return ResourceManager.GetString("finished_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        public static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours to finish, at Sprint {0}.
        /// </summary>
        public static string Hours_to_finish {
            get {
                return ResourceManager.GetString("Hours_to_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string hrs {
            get {
                return ResourceManager.GetString("hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs left.
        /// </summary>
        public static string hrs_left {
            get {
                return ResourceManager.GetString("hrs_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left hours to finish the project.
        /// </summary>
        public static string hrs_left_tooltip {
            get {
                return ResourceManager.GetString("hrs_left_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal hours.
        /// </summary>
        public static string Ideal_hours {
            get {
                return ResourceManager.GetString("Ideal_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of hours that a regular team member would take to finish this story.
        /// </summary>
        public static string Ideal_hours_tooltip {
            get {
                return ResourceManager.GetString("Ideal_hours_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase business priority.
        /// </summary>
        public static string Increase_business_priority {
            get {
                return ResourceManager.GetString("Increase_business_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string Is_active {
            get {
                return ResourceManager.GetString("Is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue only.
        /// </summary>
        public static string Issue_only {
            get {
                return ResourceManager.GetString("Issue_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planning of this item is late.
        /// </summary>
        public static string Item_is_late {
            get {
                return ResourceManager.GetString("Item_is_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story points.
        /// </summary>
        public static string Item_sizes {
            get {
                return ResourceManager.GetString("Item_sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (last planned at sprint {0}).
        /// </summary>
        public static string last_planned_at {
            get {
                return ResourceManager.GetString("last_planned_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string N_days {
            get {
                return ResourceManager.GetString("N_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} hours left.
        /// </summary>
        public static string N_hours_left {
            get {
                return ResourceManager.GetString("N_hours_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} hrs.
        /// </summary>
        public static string N_hrs {
            get {
                return ResourceManager.GetString("N_hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} planned.
        /// </summary>
        public static string N_planned {
            get {
                return ResourceManager.GetString("N_planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} pts.
        /// </summary>
        public static string N_pts {
            get {
                return ResourceManager.GetString("N_pts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} spent.
        /// </summary>
        public static string N_spent {
            get {
                return ResourceManager.GetString("N_spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string New_item {
            get {
                return ResourceManager.GetString("New_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item name.
        /// </summary>
        public static string New_item_name {
            get {
                return ResourceManager.GetString("New_item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New story.
        /// </summary>
        public static string New_size {
            get {
                return ResourceManager.GetString("New_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New struct.
        /// </summary>
        public static string New_struct {
            get {
                return ResourceManager.GetString("New_struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next item.
        /// </summary>
        public static string Next_item {
            get {
                return ResourceManager.GetString("Next_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next item (Pg dn).
        /// </summary>
        public static string Next_item_tooltip {
            get {
                return ResourceManager.GetString("Next_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string next_sprint {
            get {
                return ResourceManager.GetString("next_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backlog items were found..
        /// </summary>
        public static string No_items_were_found {
            get {
                return ResourceManager.GetString("No_items_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backlog is empty or no items match your seach criteria.
        ///You can search for a item using its name ou number..
        /// </summary>
        public static string No_items_were_found_tip {
            get {
                return ResourceManager.GetString("No_items_were_found_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stoty was informed for this item..
        /// </summary>
        public static string no_story {
            get {
                return ResourceManager.GetString("no_story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One unit point.
        /// </summary>
        public static string One_unit_point {
            get {
                return ResourceManager.GetString("One_unit_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with proposal planning.
        /// </summary>
        public static string P_tooltip {
            get {
                return ResourceManager.GetString("P_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasting items.
        /// </summary>
        public static string Pasting_items {
            get {
                return ResourceManager.GetString("Pasting_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to paste {0} items at this project.
        ///Are you sure?.
        /// </summary>
        public static string Pasting_items_prompt {
            get {
                return ResourceManager.GetString("Pasting_items_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan.
        /// </summary>
        public static string plan {
            get {
                return ResourceManager.GetString("plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan items.
        /// </summary>
        public static string Plan_items {
            get {
                return ResourceManager.GetString("Plan_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All late and not planned items will be planned to the current sprint.
        ///Confirm?.
        /// </summary>
        public static string Plan_items_tooltip {
            get {
                return ResourceManager.GetString("Plan_items_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and review.
        /// </summary>
        public static string PLAN_REVIEW_GROUP {
            get {
                return ResourceManager.GetString("PLAN_REVIEW_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan sprint {0}.
        /// </summary>
        public static string Plan_sprint_N {
            get {
                return ResourceManager.GetString("Plan_sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (plan).
        /// </summary>
        public static string planGroup {
            get {
                return ResourceManager.GetString("planGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string PLANNING_BACKLOG {
            get {
                return ResourceManager.GetString("PLANNING_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning items.
        /// </summary>
        public static string PLANNING_BACKLOG_tooltip {
            get {
                return ResourceManager.GetString("PLANNING_BACKLOG_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This size, is used for all the planning and review tasks of each sprint.
        /// </summary>
        public static string Planning_item_tooltip {
            get {
                return ResourceManager.GetString("Planning_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed at the sprint planning.
        /// </summary>
        public static string PLANNING_OCC {
            get {
                return ResourceManager.GetString("PLANNING_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O..
        /// </summary>
        public static string PO_ROLE_SN {
            get {
                return ResourceManager.GetString("PO_ROLE_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc price.
        /// </summary>
        public static string Preview_price {
            get {
                return ResourceManager.GetString("Preview_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous item.
        /// </summary>
        public static string Previous_item {
            get {
                return ResourceManager.GetString("Previous_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous item (Pg up).
        /// </summary>
        public static string Previous_item_tooltip {
            get {
                return ResourceManager.GetString("Previous_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string previous_sprint {
            get {
                return ResourceManager.GetString("previous_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not planned or late.
        /// </summary>
        public static string Previous_sprint_items {
            get {
                return ResourceManager.GetString("Previous_sprint_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product backlog.
        /// </summary>
        public static string PRODUCT_BACKLOG {
            get {
                return ResourceManager.GetString("PRODUCT_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items have not been planned yet.
        /// </summary>
        public static string PRODUCT_BACKLOG_tooltipo {
            get {
                return ResourceManager.GetString("PRODUCT_BACKLOG_tooltipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pts.
        /// </summary>
        public static string pts {
            get {
                return ResourceManager.GetString("pts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pts/hrs.
        /// </summary>
        public static string pts_hrs {
            get {
                return ResourceManager.GetString("pts_hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove backlog item.
        /// </summary>
        public static string Remove_backlog_item {
            get {
                return ResourceManager.GetString("Remove_backlog_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-plan.
        /// </summary>
        public static string Replan_to_current_sprint {
            get {
                return ResourceManager.GetString("Replan_to_current_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule (full).
        /// </summary>
        public static string Schedule_full_report {
            get {
                return ResourceManager.GetString("Schedule_full_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule_report {
            get {
                return ResourceManager.GetString("Schedule_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string SELECTED_BACKLOG {
            get {
                return ResourceManager.GetString("SELECTED_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sprint items.
        /// </summary>
        public static string SELECTED_BACKLOG_tooltip {
            get {
                return ResourceManager.GetString("SELECTED_BACKLOG_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns on/off the multi-item selection.
        /// </summary>
        public static string Selection_tooltip {
            get {
                return ResourceManager.GetString("Selection_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as delivery item.
        /// </summary>
        public static string Set_as_delivery_item {
            get {
                return ResourceManager.GetString("Set_as_delivery_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as planning item.
        /// </summary>
        public static string Set_as_planning_item {
            get {
                return ResourceManager.GetString("Set_as_planning_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift sprints.
        /// </summary>
        public static string Shift_sprints {
            get {
                return ResourceManager.GetString("Shift_sprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sprints will be shifted and a new sprint will be inserted before sprint {0}.
        ///Confirm? .
        /// </summary>
        public static string Shift_sprints_tooltip {
            get {
                return ResourceManager.GetString("Shift_sprints_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all sprints.
        /// </summary>
        public static string Show_all_sprints {
            get {
                return ResourceManager.GetString("Show_all_sprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showing {0}.
        /// </summary>
        public static string showing_n {
            get {
                return ResourceManager.GetString("showing_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you rather use a fixed story point table?.
        /// </summary>
        public static string SinglePoint_Off_tooltip {
            get {
                return ResourceManager.GetString("SinglePoint_Off_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of use a fixed story point table, do you rather estimate every backlog item size by your self?.
        /// </summary>
        public static string SinglePoint_On_tooltip {
            get {
                return ResourceManager.GetString("SinglePoint_On_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points to finish the project.
        /// </summary>
        public static string size_left_tooltip {
            get {
                return ResourceManager.GetString("size_left_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.M..
        /// </summary>
        public static string SM_ROLE_SN {
            get {
                return ResourceManager.GetString("SM_ROLE_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprint {0}.
        /// </summary>
        public static string sprint_N {
            get {
                return ResourceManager.GetString("sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint stack.
        /// </summary>
        public static string Sprint_stack {
            get {
                return ResourceManager.GetString("Sprint_stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprints.
        /// </summary>
        public static string Sprints {
            get {
                return ResourceManager.GetString("Sprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Start_date {
            get {
                return ResourceManager.GetString("Start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at.
        /// </summary>
        public static string started_at {
            get {
                return ResourceManager.GetString("started_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested hours based on your team velocity history..
        /// </summary>
        public static string Suggested_hours_tooltip {
            get {
                return ResourceManager.GetString("Suggested_hours_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM.
        /// </summary>
        public static string TEAM_ROLE_SN {
            get {
                return ResourceManager.GetString("TEAM_ROLE_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following items have not been planned yet.
        /// </summary>
        public static string The_following_items_have_not_been_planned_yet {
            get {
                return ResourceManager.GetString("The_following_items_have_not_been_planned_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a sprint plan/delivery activity and can not be re-planed once the sprint is over.
        ///Change this item status to done..
        /// </summary>
        public static string This_is_a_plan_item_can_not_be_replaned {
            get {
                return ResourceManager.GetString("This_is_a_plan_item_can_not_be_replaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket projects do not have sprints. Instead, they have a continuous backlog that is prioritized and delivered as the client requests..
        /// </summary>
        public static string Ticket_project_alert {
            get {
                return ResourceManager.GetString("Ticket_project_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be done using.
        /// </summary>
        public static string to_be_done_using {
            get {
                return ResourceManager.GetString("to_be_done_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to current.
        /// </summary>
        public static string to_current {
            get {
                return ResourceManager.GetString("to_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to last.
        /// </summary>
        public static string to_last {
            get {
                return ResourceManager.GetString("to_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to next.
        /// </summary>
        public static string to_next {
            get {
                return ResourceManager.GetString("to_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to previous.
        /// </summary>
        public static string to_previous {
            get {
                return ResourceManager.GetString("to_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to Product Backlog.
        /// </summary>
        public static string to_product_backlog {
            get {
                return ResourceManager.GetString("to_product_backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string TODO_BACKLOG {
            get {
                return ResourceManager.GetString("TODO_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items that have not been finished yet.
        /// </summary>
        public static string TODO_BACKLOG_tooltip {
            get {
                return ResourceManager.GetString("TODO_BACKLOG_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use fixed points.
        /// </summary>
        public static string use_fixed_points {
            get {
                return ResourceManager.GetString("use_fixed_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use flexibe points.
        /// </summary>
        public static string use_flexibe_points {
            get {
                return ResourceManager.GetString("use_flexibe_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use avareage hours.
        /// </summary>
        public static string use_hitorical_hours {
            get {
                return ResourceManager.GetString("use_hitorical_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use ideal hours.
        /// </summary>
        public static string use_ideal_hours {
            get {
                return ResourceManager.GetString("use_ideal_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required velocity to finish the project.
        /// </summary>
        public static string velocity_tooltip {
            get {
                return ResourceManager.GetString("velocity_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string View_details {
            get {
                return ResourceManager.GetString("View_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % walked.
        /// </summary>
        public static string walked {
            get {
                return ResourceManager.GetString("walked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work days.
        /// </summary>
        public static string work_days {
            get {
                return ResourceManager.GetString("work_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task to me.
        /// </summary>
        public static string work_on_it {
            get {
                return ResourceManager.GetString("work_on_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work structures.
        /// </summary>
        public static string Work_structures {
            get {
                return ResourceManager.GetString("Work_structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        public static string x_size_factor {
            get {
                return ResourceManager.GetString("x_size_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a scrum master to paste items.
        /// </summary>
        public static string You_need_to_be_a_scrum_master_to_paste_items {
            get {
                return ResourceManager.GetString("You_need_to_be_a_scrum_master_to_paste_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide the item size in order to get the suggested hours.
        /// </summary>
        public static string You_need_to_provide_the_item_size {
            get {
                return ResourceManager.GetString("You_need_to_provide_the_item_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be needed {0:0.#} guys to perform this sprint.
        /// </summary>
        public static string You_will_need_N_guys_to_perform_this_sprint {
            get {
                return ResourceManager.GetString("You_will_need_N_guys_to_perform_this_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current backlog size is.
        /// </summary>
        public static string Your_current_backlog_size_is {
            get {
                return ResourceManager.GetString("Your_current_backlog_size_is", resourceCulture);
            }
        }
    }
}
