//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Backlog.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.Backlog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add sprint.
        /// </summary>
        public static string Add_sprint {
            get {
                return ResourceManager.GetString("Add_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a all.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All.
        /// </summary>
        public static string ALL_BACKLOG {
            get {
                return ResourceManager.GetString("ALL_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All items.
        /// </summary>
        public static string ALL_BACKLOG_tooltip {
            get {
                return ResourceManager.GetString("ALL_BACKLOG_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a any date.
        /// </summary>
        public static string any_date {
            get {
                return ResourceManager.GetString("any_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure you want to remove the &apos;{0}&apos; backlog item?.
        /// </summary>
        public static string Are_you_sure_remove_item {
            get {
                return ResourceManager.GetString("Are_you_sure_remove_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a at.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a at this date.
        /// </summary>
        public static string at_this_date {
            get {
                return ResourceManager.GetString("at_this_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Backlog.
        /// </summary>
        public static string Backlog {
            get {
                return ResourceManager.GetString("Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Backlog item.
        /// </summary>
        public static string Backlog_item {
            get {
                return ResourceManager.GetString("Backlog_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Backlog Item {0}.
        /// </summary>
        public static string Backlog_Item_0 {
            get {
                return ResourceManager.GetString("Backlog_Item_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Can not remove a backlog item that has been already planned..
        /// </summary>
        public static string BRE_CAN_DELETE_ALREADY_PLANNED_ITEM_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ALREADY_PLANNED_ITEM_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not remove the Backlog item.
        /// </summary>
        public static string BRE_CAN_DELETE_ALREADY_PLANNED_ITEM_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ALREADY_PLANNED_ITEM_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Items at proposals can not be removed from the backlog..
        /// </summary>
        public static string BRE_CAN_DELETE_ITEM_AT_PROPOSAL_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ITEM_AT_PROPOSAL_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not remove the Backlog item.
        /// </summary>
        public static string BRE_CAN_DELETE_ITEM_AT_PROPOSAL_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ITEM_AT_PROPOSAL_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Backlog items with assigned tasks can not be removed..
        /// </summary>
        public static string BRE_CAN_DELETE_ITEM_WITH_TASKS_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ITEM_WITH_TASKS_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not remove the Backlog item.
        /// </summary>
        public static string BRE_CAN_DELETE_ITEM_WITH_TASKS_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_DELETE_ITEM_WITH_TASKS_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not change the sprint end date.
        ///It should be a date after the sprint start date..
        /// </summary>
        public static string BRE_END_DATE_NOT_ALLOWED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_END_DATE_NOT_ALLOWED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Can not remove a item size that has been already used at a project.
        ///You still can disable it..
        /// </summary>
        public static string BRE_ITEM_SIZE_ALREADY_USED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_ITEM_SIZE_ALREADY_USED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not remove item size.
        /// </summary>
        public static string BRE_ITEM_SIZE_ALREADY_USED_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_ITEM_SIZE_ALREADY_USED_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The default Plan and Delivery item sizes can not be deleted..
        /// </summary>
        public static string BRE_PLAN_ITEM_SIZE_CAN_NOT_BE_DELETED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_PLAN_ITEM_SIZE_CAN_NOT_BE_DELETED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not remove item size.
        /// </summary>
        public static string BRE_PLAN_ITEM_SIZE_CAN_NOT_BE_DELETED_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_PLAN_ITEM_SIZE_CAN_NOT_BE_DELETED_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not change the sprint start date.
        ///It should be a date after the previuos sprint start date..
        /// </summary>
        public static string BRE_SPRINT_START_DATE_NOT_ALLOWED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_SPRINT_START_DATE_NOT_ALLOWED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sprint date change not allowed.
        /// </summary>
        public static string BRE_SPRINT_START_DATE_NOT_ALLOWED_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_SPRINT_START_DATE_NOT_ALLOWED_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compare with current planning.
        /// </summary>
        public static string C_tooltip {
            get {
                return ResourceManager.GetString("C_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a calculating....
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This item was planned at sprint {0} that is now over.
        ///If you want to change the planned hours to the current sprint click at the re-plan button.
        ///If the item is finished change the item status..
        /// </summary>
        public static string Can_not_change_item_hours {
            get {
                return ResourceManager.GetString("Can_not_change_item_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It is not possible to change item planned hours.
        /// </summary>
        public static string Can_not_change_item_hours_Title {
            get {
                return ResourceManager.GetString("Can_not_change_item_hours_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change it.
        /// </summary>
        public static string Change_it {
            get {
                return ResourceManager.GetString("Change_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change log.
        /// </summary>
        public static string Change_log {
            get {
                return ResourceManager.GetString("Change_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a click here to see suggested hours.
        /// </summary>
        public static string click_here_to_see_suggested_hours {
            get {
                return ResourceManager.GetString("click_here_to_see_suggested_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ctrl-C to copy.
        /// </summary>
        public static string copyitems_tooltip {
            get {
                return ResourceManager.GetString("copyitems_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not paste items.
        /// </summary>
        public static string Could_not_paste_items {
            get {
                return ResourceManager.GetString("Could_not_paste_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not suggest hours.
        /// </summary>
        public static string Could_not_suggest_hours {
            get {
                return ResourceManager.GetString("Could_not_suggest_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a current.
        /// </summary>
        public static string current_sprint {
            get {
                return ResourceManager.GetString("current_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a dd/MMM.
        /// </summary>
        public static string dd_MMM {
            get {
                return ResourceManager.GetString("dd_MMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Decrease business priority.
        /// </summary>
        public static string Decrease_business_priority {
            get {
                return ResourceManager.GetString("Decrease_business_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delivery this item at.
        /// </summary>
        public static string Delivery_at {
            get {
                return ResourceManager.GetString("Delivery_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delivery this item at the end of the sprint.
        /// </summary>
        public static string Delivery_at_the_end_of_the_sprint {
            get {
                return ResourceManager.GetString("Delivery_at_the_end_of_the_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deliveries.
        /// </summary>
        public static string DELIVERY_GROUP {
            get {
                return ResourceManager.GetString("DELIVERY_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This size is uesed for all delivery tasls of each sprint.
        /// </summary>
        public static string Delivery_item_tooltip {
            get {
                return ResourceManager.GetString("Delivery_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fixed at the sprint end.
        /// </summary>
        public static string DELIVERY_OCC {
            get {
                return ResourceManager.GetString("DELIVERY_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delivery report.
        /// </summary>
        public static string Delivery_report {
            get {
                return ResourceManager.GetString("Delivery_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delivery sprint {0}.
        /// </summary>
        public static string Delivery_sprint_N {
            get {
                return ResourceManager.GetString("Delivery_sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (delivery).
        /// </summary>
        public static string deliveryGroup {
            get {
                return ResourceManager.GetString("deliveryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As a &lt;user type&gt; I want to &lt;do some action&gt; so that &lt;desired result&gt;.
        /// </summary>
        public static string Description_tooltip {
            get {
                return ResourceManager.GetString("Description_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Development.
        /// </summary>
        public static string DEV_GROUP {
            get {
                return ResourceManager.GetString("DEV_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Along the sprint.
        /// </summary>
        public static string DEVELOPMENT_OCC {
            get {
                return ResourceManager.GetString("DEVELOPMENT_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Drop items here.
        /// </summary>
        public static string Drop_items_here {
            get {
                return ResourceManager.GetString("Drop_items_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Due to.
        /// </summary>
        public static string Due_to {
            get {
                return ResourceManager.GetString("Due_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a End date.
        /// </summary>
        public static string End_date {
            get {
                return ResourceManager.GetString("End_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a end of sprint.
        /// </summary>
        public static string end_of_the_sprint {
            get {
                return ResourceManager.GetString("end_of_the_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a end of sprint {0}.
        /// </summary>
        public static string end_of_the_sprint_N {
            get {
                return ResourceManager.GetString("end_of_the_sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The backlog items will be equality distributed between the remaining sprints.
        ///Confirm?.
        /// </summary>
        public static string Equalise_tooltip {
            get {
                return ResourceManager.GetString("Equalise_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Equalize.
        /// </summary>
        public static string Equalize {
            get {
                return ResourceManager.GetString("Equalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id.
        /// </summary>
        public static string ExternalId {
            get {
                return ResourceManager.GetString("ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1o.
        /// </summary>
        public static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compare with first planning.
        /// </summary>
        public static string F_tooltip {
            get {
                return ResourceManager.GetString("F_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a finished at.
        /// </summary>
        public static string finished_at {
            get {
                return ResourceManager.GetString("finished_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a hide.
        /// </summary>
        public static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hours to finish, at Sprint {0}.
        /// </summary>
        public static string Hours_to_finish {
            get {
                return ResourceManager.GetString("Hours_to_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a hrs.
        /// </summary>
        public static string hrs {
            get {
                return ResourceManager.GetString("hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a hrs left.
        /// </summary>
        public static string hrs_left {
            get {
                return ResourceManager.GetString("hrs_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a left hours to finish the project.
        /// </summary>
        public static string hrs_left_tooltip {
            get {
                return ResourceManager.GetString("hrs_left_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ideal hours.
        /// </summary>
        public static string Ideal_hours {
            get {
                return ResourceManager.GetString("Ideal_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Amount of hours that a regular team member would take to finish this story.
        /// </summary>
        public static string Ideal_hours_tooltip {
            get {
                return ResourceManager.GetString("Ideal_hours_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Increase business priority.
        /// </summary>
        public static string Increase_business_priority {
            get {
                return ResourceManager.GetString("Increase_business_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Is active.
        /// </summary>
        public static string Is_active {
            get {
                return ResourceManager.GetString("Is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Issue only.
        /// </summary>
        public static string Issue_only {
            get {
                return ResourceManager.GetString("Issue_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The planning of this item is late.
        /// </summary>
        public static string Item_is_late {
            get {
                return ResourceManager.GetString("Item_is_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Story points.
        /// </summary>
        public static string Item_sizes {
            get {
                return ResourceManager.GetString("Item_sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (last planned at sprint {0}).
        /// </summary>
        public static string last_planned_at {
            get {
                return ResourceManager.GetString("last_planned_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} days.
        /// </summary>
        public static string N_days {
            get {
                return ResourceManager.GetString("N_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:0.#} hours left.
        /// </summary>
        public static string N_hours_left {
            get {
                return ResourceManager.GetString("N_hours_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:0.#} hrs.
        /// </summary>
        public static string N_hrs {
            get {
                return ResourceManager.GetString("N_hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:0.#} planned.
        /// </summary>
        public static string N_planned {
            get {
                return ResourceManager.GetString("N_planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:0} pts.
        /// </summary>
        public static string N_pts {
            get {
                return ResourceManager.GetString("N_pts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:0.#} spent.
        /// </summary>
        public static string N_spent {
            get {
                return ResourceManager.GetString("N_spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add item.
        /// </summary>
        public static string New_item {
            get {
                return ResourceManager.GetString("New_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New item name.
        /// </summary>
        public static string New_item_name {
            get {
                return ResourceManager.GetString("New_item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New story.
        /// </summary>
        public static string New_size {
            get {
                return ResourceManager.GetString("New_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New struct.
        /// </summary>
        public static string New_struct {
            get {
                return ResourceManager.GetString("New_struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next item.
        /// </summary>
        public static string Next_item {
            get {
                return ResourceManager.GetString("Next_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next item (Pg dn).
        /// </summary>
        public static string Next_item_tooltip {
            get {
                return ResourceManager.GetString("Next_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a next.
        /// </summary>
        public static string next_sprint {
            get {
                return ResourceManager.GetString("next_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No backlog items were found..
        /// </summary>
        public static string No_items_were_found {
            get {
                return ResourceManager.GetString("No_items_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The backlog is empty or no items match your seach criteria.
        ///You can search for a item using its name ou number..
        /// </summary>
        public static string No_items_were_found_tip {
            get {
                return ResourceManager.GetString("No_items_were_found_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No stoty was informed for this item..
        /// </summary>
        public static string no_story {
            get {
                return ResourceManager.GetString("no_story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One unit point.
        /// </summary>
        public static string One_unit_point {
            get {
                return ResourceManager.GetString("One_unit_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a P.
        /// </summary>
        public static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compare with proposal planning.
        /// </summary>
        public static string P_tooltip {
            get {
                return ResourceManager.GetString("P_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pasting items.
        /// </summary>
        public static string Pasting_items {
            get {
                return ResourceManager.GetString("Pasting_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You are about to paste {0} items at this project.
        ///Are you sure?.
        /// </summary>
        public static string Pasting_items_prompt {
            get {
                return ResourceManager.GetString("Pasting_items_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a plan.
        /// </summary>
        public static string plan {
            get {
                return ResourceManager.GetString("plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plan items.
        /// </summary>
        public static string Plan_items {
            get {
                return ResourceManager.GetString("Plan_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All late and not planned items will be planned to the current sprint.
        ///Confirm?.
        /// </summary>
        public static string Plan_items_tooltip {
            get {
                return ResourceManager.GetString("Plan_items_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plan and review.
        /// </summary>
        public static string PLAN_REVIEW_GROUP {
            get {
                return ResourceManager.GetString("PLAN_REVIEW_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plan sprint {0}.
        /// </summary>
        public static string Plan_sprint_N {
            get {
                return ResourceManager.GetString("Plan_sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (plan).
        /// </summary>
        public static string planGroup {
            get {
                return ResourceManager.GetString("planGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Planning.
        /// </summary>
        public static string PLANNING_BACKLOG {
            get {
                return ResourceManager.GetString("PLANNING_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Planning items.
        /// </summary>
        public static string PLANNING_BACKLOG_tooltip {
            get {
                return ResourceManager.GetString("PLANNING_BACKLOG_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This size, is used for all the planning and review tasks of each sprint.
        /// </summary>
        public static string Planning_item_tooltip {
            get {
                return ResourceManager.GetString("Planning_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fixed at the sprint planning.
        /// </summary>
        public static string PLANNING_OCC {
            get {
                return ResourceManager.GetString("PLANNING_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a P.O..
        /// </summary>
        public static string PO_ROLE_SN {
            get {
                return ResourceManager.GetString("PO_ROLE_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Calc price.
        /// </summary>
        public static string Preview_price {
            get {
                return ResourceManager.GetString("Preview_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Previous item.
        /// </summary>
        public static string Previous_item {
            get {
                return ResourceManager.GetString("Previous_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Previous item (Pg up).
        /// </summary>
        public static string Previous_item_tooltip {
            get {
                return ResourceManager.GetString("Previous_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a previous.
        /// </summary>
        public static string previous_sprint {
            get {
                return ResourceManager.GetString("previous_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not planned or late.
        /// </summary>
        public static string Previous_sprint_items {
            get {
                return ResourceManager.GetString("Previous_sprint_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product backlog.
        /// </summary>
        public static string PRODUCT_BACKLOG {
            get {
                return ResourceManager.GetString("PRODUCT_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Items have not been planned yet.
        /// </summary>
        public static string PRODUCT_BACKLOG_tooltipo {
            get {
                return ResourceManager.GetString("PRODUCT_BACKLOG_tooltipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pts.
        /// </summary>
        public static string pts {
            get {
                return ResourceManager.GetString("pts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pts/hrs.
        /// </summary>
        public static string pts_hrs {
            get {
                return ResourceManager.GetString("pts_hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove backlog item.
        /// </summary>
        public static string Remove_backlog_item {
            get {
                return ResourceManager.GetString("Remove_backlog_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-plan.
        /// </summary>
        public static string Replan_to_current_sprint {
            get {
                return ResourceManager.GetString("Replan_to_current_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Schedule (full).
        /// </summary>
        public static string Schedule_full_report {
            get {
                return ResourceManager.GetString("Schedule_full_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Schedule.
        /// </summary>
        public static string Schedule_report {
            get {
                return ResourceManager.GetString("Schedule_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selected.
        /// </summary>
        public static string SELECTED_BACKLOG {
            get {
                return ResourceManager.GetString("SELECTED_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current sprint items.
        /// </summary>
        public static string SELECTED_BACKLOG_tooltip {
            get {
                return ResourceManager.GetString("SELECTED_BACKLOG_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turns on/off the multi-item selection.
        /// </summary>
        public static string Selection_tooltip {
            get {
                return ResourceManager.GetString("Selection_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set as delivery item.
        /// </summary>
        public static string Set_as_delivery_item {
            get {
                return ResourceManager.GetString("Set_as_delivery_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set as planning item.
        /// </summary>
        public static string Set_as_planning_item {
            get {
                return ResourceManager.GetString("Set_as_planning_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shift sprints.
        /// </summary>
        public static string Shift_sprints {
            get {
                return ResourceManager.GetString("Shift_sprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All sprints will be shifted and a new sprint will be inserted before sprint {0}.
        ///Confirm? .
        /// </summary>
        public static string Shift_sprints_tooltip {
            get {
                return ResourceManager.GetString("Shift_sprints_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show all sprints.
        /// </summary>
        public static string Show_all_sprints {
            get {
                return ResourceManager.GetString("Show_all_sprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a showing {0}.
        /// </summary>
        public static string showing_n {
            get {
                return ResourceManager.GetString("showing_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you rather use a fixed story point table?.
        /// </summary>
        public static string SinglePoint_Off_tooltip {
            get {
                return ResourceManager.GetString("SinglePoint_Off_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instead of use a fixed story point table, do you rather estimate every backlog item size by your self?.
        /// </summary>
        public static string SinglePoint_On_tooltip {
            get {
                return ResourceManager.GetString("SinglePoint_On_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Points.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a points to finish the project.
        /// </summary>
        public static string size_left_tooltip {
            get {
                return ResourceManager.GetString("size_left_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a S.M..
        /// </summary>
        public static string SM_ROLE_SN {
            get {
                return ResourceManager.GetString("SM_ROLE_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a sprint {0}.
        /// </summary>
        public static string sprint_N {
            get {
                return ResourceManager.GetString("sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sprint stack.
        /// </summary>
        public static string Sprint_stack {
            get {
                return ResourceManager.GetString("Sprint_stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sprints.
        /// </summary>
        public static string Sprints {
            get {
                return ResourceManager.GetString("Sprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start date.
        /// </summary>
        public static string Start_date {
            get {
                return ResourceManager.GetString("Start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Started at.
        /// </summary>
        public static string started_at {
            get {
                return ResourceManager.GetString("started_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Story.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Suggested hours based on your team velocity history..
        /// </summary>
        public static string Suggested_hours_tooltip {
            get {
                return ResourceManager.GetString("Suggested_hours_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TEAM.
        /// </summary>
        public static string TEAM_ROLE_SN {
            get {
                return ResourceManager.GetString("TEAM_ROLE_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The following items have not been planned yet.
        /// </summary>
        public static string The_following_items_have_not_been_planned_yet {
            get {
                return ResourceManager.GetString("The_following_items_have_not_been_planned_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This is a sprint plan/delivery activity and can not be re-planed once the sprint is over.
        ///Change this item status to done..
        /// </summary>
        public static string This_is_a_plan_item_can_not_be_replaned {
            get {
                return ResourceManager.GetString("This_is_a_plan_item_can_not_be_replaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ticket projects do not have sprints. Instead, they have a continuous backlog that is prioritized and delivered as the client requests..
        /// </summary>
        public static string Ticket_project_alert {
            get {
                return ResourceManager.GetString("Ticket_project_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to be done using.
        /// </summary>
        public static string to_be_done_using {
            get {
                return ResourceManager.GetString("to_be_done_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to current.
        /// </summary>
        public static string to_current {
            get {
                return ResourceManager.GetString("to_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to last.
        /// </summary>
        public static string to_last {
            get {
                return ResourceManager.GetString("to_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to next.
        /// </summary>
        public static string to_next {
            get {
                return ResourceManager.GetString("to_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to previous.
        /// </summary>
        public static string to_previous {
            get {
                return ResourceManager.GetString("to_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to Product Backlog.
        /// </summary>
        public static string to_product_backlog {
            get {
                return ResourceManager.GetString("to_product_backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pending.
        /// </summary>
        public static string TODO_BACKLOG {
            get {
                return ResourceManager.GetString("TODO_BACKLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Items that have not been finished yet.
        /// </summary>
        public static string TODO_BACKLOG_tooltip {
            get {
                return ResourceManager.GetString("TODO_BACKLOG_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use fixed points.
        /// </summary>
        public static string use_fixed_points {
            get {
                return ResourceManager.GetString("use_fixed_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use flexibe points.
        /// </summary>
        public static string use_flexibe_points {
            get {
                return ResourceManager.GetString("use_flexibe_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a use avareage hours.
        /// </summary>
        public static string use_hitorical_hours {
            get {
                return ResourceManager.GetString("use_hitorical_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a use ideal hours.
        /// </summary>
        public static string use_ideal_hours {
            get {
                return ResourceManager.GetString("use_ideal_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a required velocity to finish the project.
        /// </summary>
        public static string velocity_tooltip {
            get {
                return ResourceManager.GetString("velocity_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a View details.
        /// </summary>
        public static string View_details {
            get {
                return ResourceManager.GetString("View_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a % walked.
        /// </summary>
        public static string walked {
            get {
                return ResourceManager.GetString("walked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a work days.
        /// </summary>
        public static string work_days {
            get {
                return ResourceManager.GetString("work_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a add task to me.
        /// </summary>
        public static string work_on_it {
            get {
                return ResourceManager.GetString("work_on_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Work structures.
        /// </summary>
        public static string Work_structures {
            get {
                return ResourceManager.GetString("Work_structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a x.
        /// </summary>
        public static string x_size_factor {
            get {
                return ResourceManager.GetString("x_size_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You need to be a scrum master to paste items.
        /// </summary>
        public static string You_need_to_be_a_scrum_master_to_paste_items {
            get {
                return ResourceManager.GetString("You_need_to_be_a_scrum_master_to_paste_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You need to provide the item size in order to get the suggested hours.
        /// </summary>
        public static string You_need_to_provide_the_item_size {
            get {
                return ResourceManager.GetString("You_need_to_provide_the_item_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Will be needed {0:0.#} guys to perform this sprint.
        /// </summary>
        public static string You_will_need_N_guys_to_perform_this_sprint {
            get {
                return ResourceManager.GetString("You_will_need_N_guys_to_perform_this_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current backlog size is.
        /// </summary>
        public static string Your_current_backlog_size_is {
            get {
                return ResourceManager.GetString("Your_current_backlog_size_is", resourceCulture);
            }
        }
    }
}
