//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.ProjectConstraints.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.ProjectConstraints.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x0.8.
        /// </summary>
        public static string _08 {
            get {
                return ResourceManager.GetString("_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x1.0.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x1.2.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_constraint {
            get {
                return ResourceManager.GetString("Add_constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjusted points.
        /// </summary>
        public static string adjusted_points {
            get {
                return ResourceManager.GetString("adjusted_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string BROWSER_CONSTRAINT {
            get {
                return ResourceManager.GetString("BROWSER_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string BUSINESS_CONSTRAINT {
            get {
                return ResourceManager.GetString("BUSINESS_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint.
        /// </summary>
        public static string Constraint {
            get {
                return ResourceManager.GetString("Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraints.
        /// </summary>
        public static string Constraints {
            get {
                return ResourceManager.GetString("Constraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string DATABASE_CONSTRAINT {
            get {
                return ResourceManager.GetString("DATABASE_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DEVICE_CONSTRAINT {
            get {
                return ResourceManager.GetString("DEVICE_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string ENVIRONMENT_CONSTRAINT {
            get {
                return ResourceManager.GetString("ENVIRONMENT_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project does not have any constraints..
        /// </summary>
        public static string No_constraints_found {
            get {
                return ResourceManager.GetString("No_constraints_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no suggestions avaialble. Ask the Factory Owner to config them using an XML file at the server-side..
        /// </summary>
        public static string no_suggestions {
            get {
                return ResourceManager.GetString("no_suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show suggestions.
        /// </summary>
        public static string Show_suggestions {
            get {
                return ResourceManager.GetString("Show_suggestions", resourceCulture);
            }
        }
    }
}
