//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.FactoryServerConfiguration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.FactoryServerConfiguration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string DefaultCompanyName {
            get {
                return ResourceManager.GetString("DefaultCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory e-mail account.
        /// </summary>
        public static string ScrumFactorySenderEmail {
            get {
                return ResourceManager.GetString("ScrumFactorySenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory e-mail name.
        /// </summary>
        public static string ScrumFactorySenderName {
            get {
                return ResourceManager.GetString("ScrumFactorySenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        public static string Server_settings {
            get {
                return ResourceManager.GetString("Server_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted e-mail domains.
        /// </summary>
        public static string TrustedEmailDomains {
            get {
                return ResourceManager.GetString("TrustedEmailDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users from those domains will be automatically created when they first try to sign in.
        /// </summary>
        public static string TrustedEmailDomains_tooltip {
            get {
                return ResourceManager.GetString("TrustedEmailDomains_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload logo.
        /// </summary>
        public static string Upload_logo {
            get {
                return ResourceManager.GetString("Upload_logo", resourceCulture);
            }
        }
    }
}
