//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifact
    {
        public string ArtifactUId { get; set; }
        public string ProjectUId { get; set; }
        public string ContextUId { get; set; }
        public string ArtifactName { get; set; }
        public string ArtifactPath { get; set; }
        public short ArtifactContext { get; set; }
    }
}
