//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberProfile
    {
        public MemberProfile()
        {
            this.Memberships = new HashSet<ProjectMembership>();
        }
    
        public string MemberUId { get; set; }
        public string FullName { get; set; }
        public string EmailAccount { get; set; }
        public string CompanyName { get; set; }
        public string Skills { get; set; }
        public string ContactData { get; set; }
        public string AuthorizationProvider { get; set; }
        public bool IsFactoryOwner { get; set; }
        public bool CanSeeProposalValues { get; set; }
        public string CreateBy { get; set; }
        public bool IsActive { get; set; }
        public string TeamCode { get; set; }
    
        public virtual ICollection<ProjectMembership> Memberships { get; set; }
    }
}
