//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMembership
    {
        public string ProjectUId { get; set; }
        public string MemberUId { get; set; }
        public string RoleUId { get; set; }
        public Nullable<int> DayAllocation { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> InactiveSince { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
