//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectConstraint
    {
        public string ConstraintUId { get; set; }
        public string ProjectUId { get; set; }
        public string ConstraintId { get; set; }
        public string Constraint { get; set; }
        public short ConstraintGroup { get; set; }
        public double AdjustPointFactor { get; set; }
    }
}
