//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Sprints = new HashSet<Sprint>();
            this.Roles = new HashSet<Role>();
            this.Memberships = new HashSet<ProjectMembership>();
        }
    
        public string ProjectUId { get; set; }
        public int ProjectNumber { get; set; }
        public string ProjectName { get; set; }
        public string ClientName { get; set; }
        public short Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CreateBy { get; set; }
        public string CodeRepositoryPath { get; set; }
        public string DocRepositoryPath { get; set; }
        public string Platform { get; set; }
        public bool IsSuspended { get; set; }
        public bool AnyoneCanJoin { get; set; }
        public short ProjectType { get; set; }
        public Nullable<int> Baseline { get; set; }
    
        public virtual ICollection<Sprint> Sprints { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<ProjectMembership> Memberships { get; set; }
    }
}
