//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        public string RiskUId { get; set; }
        public string ProjectUId { get; set; }
        public string RiskDescription { get; set; }
        public System.DateTime CreateDate { get; set; }
        public short Impact { get; set; }
        public short Probability { get; set; }
        public string RiskAction { get; set; }
        public bool IsPrivate { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    }
}
