//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.PlannedHours = new HashSet<PlannedHour>();
        }
    
        public string RoleUId { get; set; }
        public string RoleName { get; set; }
        public string ProjectUId { get; set; }
        public string RoleDescription { get; set; }
        public short PermissionSet { get; set; }
        public bool IsPlanned { get; set; }
        public string RoleShortName { get; set; }
        public bool IsDefaultRole { get; set; }
    
        public virtual ICollection<PlannedHour> PlannedHours { get; set; }
    }
}
