//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScrumFactoryEntities : DbContext
    {
        public ScrumFactoryEntities()
            : base("name=ScrumFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BacklogItem> BacklogItems { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<PlannedHour> PlannedHours { get; set; }
        public DbSet<Sprint> Sprints { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<MemberProfile> MemberProfiles { get; set; }
        public DbSet<ProjectMembership> ProjectMemberships { get; set; }
        public DbSet<ItemSize> ItemSizes { get; set; }
        public DbSet<MemberAvatar> MembersAvatar { get; set; }
        public DbSet<BacklogItemEffectiveHours> BacklogItemEffectiveHours1 { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<BacklogItemGroup> BacklogItemGroups { get; set; }
        public DbSet<Proposal> Proposals { get; set; }
        public DbSet<ProposalItem> ProposalItems { get; set; }
        public DbSet<RoleHourCost> RoleHourCosts { get; set; }
        public DbSet<ProposalDocument> ProposalDocuments { get; set; }
        public DbSet<ProposalClause> ProposalClauses { get; set; }
        public DbSet<ProposalFixedCost> ProposalFixedCosts { get; set; }
        public DbSet<Risk> Risks { get; set; }
        public DbSet<TaskDetail> TaskDetails { get; set; }
        public DbSet<Artifact> Artifacts { get; set; }
        public DbSet<AuthorizationInfo> AuthorizationInfos { get; set; }
        public DbSet<SizeIdealHour> SizeIdealHours { get; set; }
        public DbSet<CalendarDay> CalendarDay { get; set; }
        public DbSet<TaskTag> TaskTags { get; set; }
        public DbSet<ProjectConstraint> ProjectConstraints { get; set; }
        public DbSet<TaskInfo> TaskInfo { get; set; }
    }
}
