//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string TaskUId { get; set; }
        public int TaskNumber { get; set; }
        public string TaskName { get; set; }
        public string TaskOwnerUId { get; set; }
        public string ProjectUId { get; set; }
        public string BacklogItemUId { get; set; }
        public short TaskType { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public short Status { get; set; }
        public decimal PlannedHours { get; set; }
        public decimal EffectiveHours { get; set; }
        public string TaskAssigneeUId { get; set; }
        public string RoleUId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public short Priority { get; set; }
        public bool IsAccounting { get; set; }
        public Nullable<int> ArtifactCount { get; set; }
        public string TagUId { get; set; }
    
        public virtual TaskDetail TaskDetail { get; set; }
        public virtual TaskInfo TaskInfo { get; set; }
    }
}
