//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskInfo
    {
        public string TaskUId { get; set; }
        public int ProjectNumber { get; set; }
        public string ProjectName { get; set; }
        public int BacklogItemNumber { get; set; }
        public string BacklogItemName { get; set; }
        public string ClientName { get; set; }
    }
}
