//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} days left).
        /// </summary>
        public static string _N_days_left {
            get {
                return ResourceManager.GetString("_N_days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Scrum Factory.
        /// </summary>
        public static string About_Scrum_Factory {
            get {
                return ResourceManager.GetString("About_Scrum_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After deployment bug.
        /// </summary>
        public static string AFTER_DEPLOY_BUG_TASK {
            get {
                return ResourceManager.GetString("AFTER_DEPLOY_BUG_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show on start up.
        /// </summary>
        public static string Always_show_on_startup {
            get {
                return ResourceManager.GetString("Always_show_on_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsers.
        /// </summary>
        public static string BROWSER_CONSTRAINT {
            get {
                return ResourceManager.GetString("BROWSER_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string BUG_TASK {
            get {
                return ResourceManager.GetString("BUG_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string BUSINESS_CONSTRAINT {
            get {
                return ResourceManager.GetString("BUSINESS_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string CANCELED_TASK {
            get {
                return ResourceManager.GetString("CANCELED_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-start Scrum Factory?.
        /// </summary>
        public static string ChangeLanguageHeader {
            get {
                return ResourceManager.GetString("ChangeLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scrum Factory need to be re-started in order to apply your changes.
        ///Re-start now?.
        /// </summary>
        public static string ChangeLanguageText {
            get {
                return ResourceManager.GetString("ChangeLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (Esc).
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Guy.
        /// </summary>
        public static string COMMERCIAL_GUY {
            get {
                return ResourceManager.GetString("COMMERCIAL_GUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Scrum Factory.
        /// </summary>
        public static string Continue_with_SF {
            get {
                return ResourceManager.GetString("Continue_with_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy project url to clipboard.
        /// </summary>
        public static string Copy_project_url_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_project_url_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical item.
        /// </summary>
        public static string CRITICAL_ITEM {
            get {
                return ResourceManager.GetString("CRITICAL_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        public static string current_sprint {
            get {
                return ResourceManager.GetString("current_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string DATABASE_CONSTRAINT {
            get {
                return ResourceManager.GetString("DATABASE_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 hours/day.
        /// </summary>
        public static string day12_allocation {
            get {
                return ResourceManager.GetString("day12_allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours/day.
        /// </summary>
        public static string day14_allocation {
            get {
                return ResourceManager.GetString("day14_allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 hours/day.
        /// </summary>
        public static string day34_allocation {
            get {
                return ResourceManager.GetString("day34_allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 hours/day.
        /// </summary>
        public static string day44_allocation {
            get {
                return ResourceManager.GetString("day44_allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 2 hours/day.
        /// </summary>
        public static string dayNull_allocation {
            get {
                return ResourceManager.GetString("dayNull_allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Item.
        /// </summary>
        public static string DELIVERY {
            get {
                return ResourceManager.GetString("DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed at the sprint end.
        /// </summary>
        public static string DELIVERY_OCC {
            get {
                return ResourceManager.GetString("DELIVERY_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Along the sprint.
        /// </summary>
        public static string DEVELOPMENT_OCC {
            get {
                return ResourceManager.GetString("DEVELOPMENT_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development task.
        /// </summary>
        public static string DEVELOPMENT_TASK {
            get {
                return ResourceManager.GetString("DEVELOPMENT_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DEVICE_CONSTRAINT {
            get {
                return ResourceManager.GetString("DEVICE_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap done_panel_img {
            get {
                object obj = ResourceManager.GetObject("done_panel_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DONE_TASK {
            get {
                return ResourceManager.GetString("DONE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English United State.
        /// </summary>
        public static string en_US_description {
            get {
                return ResourceManager.GetString("en_US_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Ticket projects (beta).
        /// </summary>
        public static string Enable_ticket_projects {
            get {
                return ResourceManager.GetString("Enable_ticket_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English - EUA.
        /// </summary>
        public static string English_eua {
            get {
                return ResourceManager.GetString("English_eua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string ENVIRONMENT_CONSTRAINT {
            get {
                return ResourceManager.GetString("ENVIRONMENT_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, could not find the report template..
        /// </summary>
        public static string Error_reading_report_template_errorMessage {
            get {
                return ResourceManager.GetString("Error_reading_report_template_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading report template.
        /// </summary>
        public static string Error_reading_report_template_errorMessageTitle {
            get {
                return ResourceManager.GetString("Error_reading_report_template_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory owners.
        /// </summary>
        public static string Factory_owners {
            get {
                return ResourceManager.GetString("Factory_owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        public static string Factory_settings {
            get {
                return ResourceManager.GetString("Factory_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon factoryIco {
            get {
                object obj = ResourceManager.GetObject("factoryIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Survey.
        /// </summary>
        public static string Feedback_survey {
            get {
                return ResourceManager.GetString("Feedback_survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are working on improve The Scrum Factory to meet your needs.
        ///Could you give us some feedback about the tool?.
        /// </summary>
        public static string Feedback_survey_text {
            get {
                return ResourceManager.GetString("Feedback_survey_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed date.
        /// </summary>
        public static string FIXED_OCC {
            get {
                return ResourceManager.GetString("FIXED_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General options.
        /// </summary>
        public static string General_options {
            get {
                return ResourceManager.GetString("General_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to &apos;{0}&apos;.
        /// </summary>
        public static string Go_back_to_project {
            get {
                return ResourceManager.GetString("Go_back_to_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to project {0}.
        /// </summary>
        public static string Go_to_project_N {
            get {
                return ResourceManager.GetString("Go_to_project_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go back to projects (F2).
        /// </summary>
        public static string go_to_projects {
            get {
                return ResourceManager.GetString("go_to_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HIGH_IMPACT_RISK {
            get {
                return ResourceManager.GetString("HIGH_IMPACT_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HIGH_PRIORITY {
            get {
                return ResourceManager.GetString("HIGH_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HIGH_PROBABILITY_RISK {
            get {
                return ResourceManager.GetString("HIGH_PROBABILITY_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impediment.
        /// </summary>
        public static string IMPEDIMENT_TASK {
            get {
                return ResourceManager.GetString("IMPEDIMENT_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement.
        /// </summary>
        public static string IMPROVEMENT_ITEM {
            get {
                return ResourceManager.GetString("IMPROVEMENT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement task.
        /// </summary>
        public static string IMPROVEMENT_TASK {
            get {
                return ResourceManager.GetString("IMPROVEMENT_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show inactives.
        /// </summary>
        public static string Inactives {
            get {
                return ResourceManager.GetString("Inactives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Interface_language {
            get {
                return ResourceManager.GetString("Interface_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement.
        /// </summary>
        public static string IPROVEMENT_TASK {
            get {
                return ResourceManager.GetString("IPROVEMENT_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string ISSUE_ITEM {
            get {
                return ResourceManager.GetString("ISSUE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item canceled.
        /// </summary>
        public static string ITEM_CANCELED {
            get {
                return ResourceManager.GetString("ITEM_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item done.
        /// </summary>
        public static string ITEM_DONE {
            get {
                return ResourceManager.GetString("ITEM_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item required.
        /// </summary>
        public static string ITEM_REQUIRED {
            get {
                return ResourceManager.GetString("ITEM_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item in progress.
        /// </summary>
        public static string ITEM_WORKING {
            get {
                return ResourceManager.GetString("ITEM_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_settings {
            get {
                return ResourceManager.GetString("Language_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageMenuItemEN {
            get {
                return ResourceManager.GetString("LanguageMenuItemEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string LanguageMenuItemPT {
            get {
                return ResourceManager.GetString("LanguageMenuItemPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LOW_IMPACT_RISK {
            get {
                return ResourceManager.GetString("LOW_IMPACT_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LOW_PROBABILITY_RISK {
            get {
                return ResourceManager.GetString("LOW_PROBABILITY_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MEDIUM_IMPACT_RISK {
            get {
                return ResourceManager.GetString("MEDIUM_IMPACT_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MEDIUM_PRIORITY {
            get {
                return ResourceManager.GetString("MEDIUM_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MEDIUM_PROBABILITY_RISK {
            get {
                return ResourceManager.GetString("MEDIUM_PROBABILITY_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/ErrorStatus/errorNetWork.png.
        /// </summary>
        public static string Microsoft_Http_HttpStageProcessingException_errorImageSource {
            get {
                return ResourceManager.GetString("Microsoft_Http_HttpStageProcessingException_errorImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the Factory Server.
        ///Verify your network connection..
        /// </summary>
        public static string Microsoft_Http_HttpStageProcessingException_errorMessage {
            get {
                return ResourceManager.GetString("Microsoft_Http_HttpStageProcessingException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the server.
        /// </summary>
        public static string Microsoft_Http_HttpStageProcessingException_errorMessageTitle {
            get {
                return ResourceManager.GetString("Microsoft_Http_HttpStageProcessingException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more....
        /// </summary>
        public static string more_ {
            get {
                return ResourceManager.GetString("more_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refine your search for more results.
        /// </summary>
        public static string More_combobox_items {
            get {
                return ResourceManager.GetString("More_combobox_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information and support access:.
        /// </summary>
        public static string More_Information {
            get {
                return ResourceManager.GetString("More_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string My_profile {
            get {
                return ResourceManager.GetString("My_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See my tasks.
        /// </summary>
        public static string My_tasks {
            get {
                return ResourceManager.GetString("My_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my tasks (F2).
        /// </summary>
        public static string my_tasks_f2 {
            get {
                return ResourceManager.GetString("my_tasks_f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} hours left.
        /// </summary>
        public static string N_hours_left {
            get {
                return ResourceManager.GetString("N_hours_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} hrs of work to do.
        /// </summary>
        public static string N_hours_of_work {
            get {
                return ResourceManager.GetString("N_hours_of_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hrs this month.
        /// </summary>
        public static string N_hrs_this_month {
            get {
                return ResourceManager.GetString("N_hrs_this_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string New_project {
            get {
                return ResourceManager.GetString("New_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next_sprint.
        /// </summary>
        public static string next_sprint {
            get {
                return ResourceManager.GetString("next_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find item match.
        /// </summary>
        public static string No_combobox_items {
            get {
                return ResourceManager.GetString("No_combobox_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NONE_IMPACT_RISK {
            get {
                return ResourceManager.GetString("NONE_IMPACT_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NONE_PROBABILITY_RISK {
            get {
                return ResourceManager.GetString("NONE_PROBABILITY_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal item.
        /// </summary>
        public static string NORMAL_ITEM {
            get {
                return ResourceManager.GetString("NORMAL_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NORMAL_PRIORITY {
            get {
                return ResourceManager.GetString("NORMAL_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string Options_ {
            get {
                return ResourceManager.GetString("Options_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS.
        /// </summary>
        public static string OS_CONSTRAINT {
            get {
                return ResourceManager.GetString("OS_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning item.
        /// </summary>
        public static string PLANNING {
            get {
                return ResourceManager.GetString("PLANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed at the sprint planning.
        /// </summary>
        public static string PLANNING_OCC {
            get {
                return ResourceManager.GetString("PLANNING_OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese - Brazil.
        /// </summary>
        public static string Portuguese_brazil {
            get {
                return ResourceManager.GetString("Portuguese_brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous sprint.
        /// </summary>
        public static string previous_sprint {
            get {
                return ResourceManager.GetString("previous_sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Owner.
        /// </summary>
        public static string PRODUCT_OWNER {
            get {
                return ResourceManager.GetString("PRODUCT_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled project.
        /// </summary>
        public static string PROJECT_CANCELED {
            get {
                return ResourceManager.GetString("PROJECT_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed project.
        /// </summary>
        public static string PROJECT_DONE {
            get {
                return ResourceManager.GetString("PROJECT_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running project.
        /// </summary>
        public static string PROJECT_STARTED {
            get {
                return ResourceManager.GetString("PROJECT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string PROJECT_SUPPORT {
            get {
                return ResourceManager.GetString("PROJECT_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Network folder.
        /// </summary>
        public static string ProjectFolderFilePath {
            get {
                return ResourceManager.GetString("ProjectFolderFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everytime you create a project a folder will be created inside this folder. (leave it blank to use server-side configuration).
        /// </summary>
        public static string ProjectFolderFilePath_tooltip {
            get {
                return ResourceManager.GetString("ProjectFolderFilePath_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved proposal.
        /// </summary>
        public static string PROPOSAL_APPROVED {
            get {
                return ResourceManager.GetString("PROPOSAL_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        public static string PROPOSAL_CREATION {
            get {
                return ResourceManager.GetString("PROPOSAL_CREATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected proposal.
        /// </summary>
        public static string PROPOSAL_REJECTED {
            get {
                return ResourceManager.GetString("PROPOSAL_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese Brazil.
        /// </summary>
        public static string pt_BR_description {
            get {
                return ResourceManager.GetString("pt_BR_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent projects.
        /// </summary>
        public static string Recent_projects {
            get {
                return ResourceManager.GetString("Recent_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rejected because the project we canceled.
        /// </summary>
        public static string REJECTED_BY_CLIENT_CANCEL {
            get {
                return ResourceManager.GetString("REJECTED_BY_CLIENT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rejected due the proposal deadline.
        /// </summary>
        public static string REJECTED_BY_DEADLINE {
            get {
                return ResourceManager.GetString("REJECTED_BY_DEADLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other proposal was used.
        /// </summary>
        public static string REJECTED_BY_OTHER_PROPOSAL {
            get {
                return ResourceManager.GetString("REJECTED_BY_OTHER_PROPOSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rejected due the proposal price.
        /// </summary>
        public static string REJECTED_BY_PRICE {
            get {
                return ResourceManager.GetString("REJECTED_BY_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i do not know the reject reason.
        /// </summary>
        public static string REJECTED_BY_UNKNOW {
            get {
                return ResourceManager.GetString("REJECTED_BY_UNKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository log settings.
        /// </summary>
        public static string Repository_log_settings {
            get {
                return ResourceManager.GetString("Repository_log_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code repository file path.
        /// </summary>
        public static string RepositoryPath {
            get {
                return ResourceManager.GetString("RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: d:\myrepositories (leave it blank to use server-side configuration).
        /// </summary>
        public static string RepositoryPath_tooltip {
            get {
                return ResourceManager.GetString("RepositoryPath_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code repository server url.
        /// </summary>
        public static string RepositoryUrl {
            get {
                return ResourceManager.GetString("RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: https://yourcompany/svn (leave it blank to use server-side configuration).
        /// </summary>
        public static string RepositoryUrl_tooltip {
            get {
                return ResourceManager.GetString("RepositoryUrl_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string RepositoryVersion {
            get {
                return ResourceManager.GetString("RepositoryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (leave it blank to use server-side configuration).
        /// </summary>
        public static string RepositoryVersion_tooltip {
            get {
                return ResourceManager.GetString("RepositoryVersion_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string REQUIRED_TASK {
            get {
                return ResourceManager.GetString("REQUIRED_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (requires re-start).
        /// </summary>
        public static string Requires_restart {
            get {
                return ResourceManager.GetString("Requires_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the Scrum Factory icon at the system trail to have fast access to your tasks.
        /// </summary>
        public static string Scrum_factory_in_background {
            get {
                return ResourceManager.GetString("Scrum_factory_in_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Master.
        /// </summary>
        public static string SCRUM_MASTER {
            get {
                return ResourceManager.GetString("SCRUM_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/ErrorStatus/errorSecurity.png.
        /// </summary>
        public static string ScrumFactory_Exceptions_ForbittenException_errorImageSource {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ForbittenException_errorImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not authorized to perform this operation..
        /// </summary>
        public static string ScrumFactory_Exceptions_ForbittenException_errorMessage {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ForbittenException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        public static string ScrumFactory_Exceptions_ForbittenException_errorMessageTitle {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ForbittenException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/ErrorStatus/errorNetWork.png.
        /// </summary>
        public static string ScrumFactory_Exceptions_NetworkException_errorImageSource {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_NetworkException_errorImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the Factory Server.
        ///Verify your network connection..
        /// </summary>
        public static string ScrumFactory_Exceptions_NetworkException_errorMessage {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_NetworkException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the server.
        /// </summary>
        public static string ScrumFactory_Exceptions_NetworkException_errorMessageTitle {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_NetworkException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item you are trying to change is no longer at the server.
        ///It may has been removed by somebody else.
        ///Try to Refresh (F5) your project..
        /// </summary>
        public static string ScrumFactory_Exceptions_NotFoundException_errorMessage {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_NotFoundException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find item.
        /// </summary>
        public static string ScrumFactory_Exceptions_NotFoundException_errorMessageTitle {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_NotFoundException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your server version does not support this feature. Please update your Scrum Factory server..
        /// </summary>
        public static string ScrumFactory_Exceptions_OldServerException_errorMessage {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_OldServerException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old server version.
        /// </summary>
        public static string ScrumFactory_Exceptions_OldServerException_errorMessageTitle {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_OldServerException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/ErrorStatus/errorServer.png.
        /// </summary>
        public static string ScrumFactory_Exceptions_ServerErrorException_errorImageSource {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ServerErrorException_errorImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error ocurred at the Factory Server. Check the log error at the server..
        /// </summary>
        public static string ScrumFactory_Exceptions_ServerErrorException_errorMessage {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ServerErrorException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string ScrumFactory_Exceptions_ServerErrorException_errorMessageTitle {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ServerErrorException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a member.
        /// </summary>
        public static string select_member_tip {
            get {
                return ResourceManager.GetString("select_member_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show points at backlog list.
        /// </summary>
        public static string Show_points_at_backlog_list {
            get {
                return ResourceManager.GetString("Show_points_at_backlog_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing....
        /// </summary>
        public static string Sigining {
            get {
                return ResourceManager.GetString("Sigining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell checker.
        /// </summary>
        public static string Spell_checker {
            get {
                return ResourceManager.GetString("Spell_checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use any Open Office dictionary. Just copy the .dic and .aff files to &quot;My Documets\Scrum Factory\SpellDics&quot; folder..
        /// </summary>
        public static string Spell_checker_tooltip {
            get {
                return ResourceManager.GetString("Spell_checker_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint length (work days).
        /// </summary>
        public static string Sprint_length {
            get {
                return ResourceManager.GetString("Sprint_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprint {0}.
        /// </summary>
        public static string sprint_N {
            get {
                return ResourceManager.GetString("sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint {0} of {1}.
        /// </summary>
        public static string Sprint_N_of_M {
            get {
                return ResourceManager.GetString("Sprint_N_of_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested hours based at your historical velocity data.
        /// </summary>
        public static string Suggested_hours_tooltip {
            get {
                return ResourceManager.GetString("Suggested_hours_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External program to open repositories.
        /// </summary>
        public static string SVN_command {
            get {
                return ResourceManager.GetString("SVN_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVN options.
        /// </summary>
        public static string SVN_options {
            get {
                return ResourceManager.GetString("SVN_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVN.
        /// </summary>
        public static string SVN_settings {
            get {
                return ResourceManager.GetString("SVN_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: C:\Program Files\TortoiseSVN\bin\TortoiseProc.exe /command:log /path:&quot;{0}&quot; /findstring:&quot;{1}&quot; /findtype:1.
        /// </summary>
        public static string SVN_tooltip {
            get {
                return ResourceManager.GetString("SVN_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task canceled.
        /// </summary>
        public static string Task_canceled {
            get {
                return ResourceManager.GetString("Task_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TEAM {
            get {
                return ResourceManager.GetString("TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test task.
        /// </summary>
        public static string TEST_TASK {
            get {
                return ResourceManager.GetString("TEST_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket projects do not have sprints. Instead, they have a continuous backlog that is prioritized and delivered as the client requests..
        /// </summary>
        public static string Ticket_project_alert {
            get {
                return ResourceManager.GetString("Ticket_project_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket projects.
        /// </summary>
        public static string Ticket_projects_settings {
            get {
                return ResourceManager.GetString("Ticket_projects_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap todo_panel_img {
            get {
                object obj = ResourceManager.GetObject("todo_panel_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for more menu options.
        /// </summary>
        public static string TopMenu_tooltip {
            get {
                return ResourceManager.GetString("TopMenu_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug killer.
        /// </summary>
        public static string TROPHY_BUG_KILLER {
            get {
                return ResourceManager.GetString("TROPHY_BUG_KILLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solved more than 3 bugs this month..
        /// </summary>
        public static string TROPHY_BUG_KILLER_tooltip {
            get {
                return ResourceManager.GetString("TROPHY_BUG_KILLER_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string TROPHY_EXPERT {
            get {
                return ResourceManager.GetString("TROPHY_EXPERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked more than 2.000 hours..
        /// </summary>
        public static string TROPHY_EXPERT_tooltip {
            get {
                return ResourceManager.GetString("TROPHY_EXPERT_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard worker.
        /// </summary>
        public static string TROPHY_HARD_WORKER {
            get {
                return ResourceManager.GetString("TROPHY_HARD_WORKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked more than 160 hours this month..
        /// </summary>
        public static string TROPHY_HARD_WORKER_tooltip {
            get {
                return ResourceManager.GetString("TROPHY_HARD_WORKER_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improver.
        /// </summary>
        public static string TROPHY_IMPROVER {
            get {
                return ResourceManager.GetString("TROPHY_IMPROVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made more than 3 improvements this month..
        /// </summary>
        public static string TROPHY_IMPROVER_tooltip {
            get {
                return ResourceManager.GetString("TROPHY_IMPROVER_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flash.
        /// </summary>
        public static string TROPHY_THE_FLASH {
            get {
                return ResourceManager.GetString("TROPHY_THE_FLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solved more than 3 tasks before the planned time..
        /// </summary>
        public static string TROPHY_THE_FLASH_tooltip {
            get {
                return ResourceManager.GetString("TROPHY_THE_FLASH_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string URGENT_PRIORITY {
            get {
                return ResourceManager.GetString("URGENT_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is new.
        /// </summary>
        public static string What_is_new {
            get {
                return ResourceManager.GetString("What_is_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on.
        /// </summary>
        public static string WORKING_ON_TASK {
            get {
                return ResourceManager.GetString("WORKING_ON_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap working_panel_img {
            get {
                object obj = ResourceManager.GetObject("working_panel_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not signed yet.
        /// </summary>
        public static string You_have_not_signed {
            get {
                return ResourceManager.GetString("You_have_not_signed", resourceCulture);
            }
        }
    }
}
