//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.Tasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  by.
        /// </summary>
        public static string _by {
            get {
                return ResourceManager.GetString("_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a backlogitem and right-click here to add a new task.
        /// </summary>
        public static string add_task_tooltip {
            get {
                return ResourceManager.GetString("add_task_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks.
        /// </summary>
        public static string All_tasks {
            get {
                return ResourceManager.GetString("All_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        public static string as_ {
            get {
                return ResourceManager.GetString("as_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assign task to me.
        /// </summary>
        public static string assign_task_to_me {
            get {
                return ResourceManager.GetString("assign_task_to_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string Assignee {
            get {
                return ResourceManager.GetString("Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , by {0}.
        /// </summary>
        public static string by_N {
            get {
                return ResourceManager.GetString("by_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create task.
        /// </summary>
        public static string Can_not_create_task {
            get {
                return ResourceManager.GetString("Can_not_create_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this task.
        /// </summary>
        public static string Cancel_task {
            get {
                return ResourceManager.GetString("Cancel_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change log.
        /// </summary>
        public static string Change_log {
            get {
                return ResourceManager.GetString("Change_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks tagged with &apos;{0}&apos; will be un-tagged. Continue?.
        /// </summary>
        public static string Confirm_remove_review_tag_N {
            get {
                return ResourceManager.GetString("Confirm_remove_review_tag_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy tag.
        /// </summary>
        public static string Copy_tag {
            get {
                return ResourceManager.GetString("Copy_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy this task tag to clipboard.
        /// </summary>
        public static string Copy_tag_tooltip {
            get {
                return ResourceManager.GetString("Copy_tag_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy track info to clipboard.
        /// </summary>
        public static string copy_track_info_to_clipboard {
            get {
                return ResourceManager.GetString("copy_track_info_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl-C to copy.
        /// </summary>
        public static string copytasks_tooltip {
            get {
                return ResourceManager.GetString("copytasks_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not paste tasks.
        /// </summary>
        public static string Could_not_paste_tasks {
            get {
                return ResourceManager.GetString("Could_not_paste_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created at {0:d/M/yyyy HH:mm}.
        /// </summary>
        public static string created_at_N {
            get {
                return ResourceManager.GetString("created_at_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish this task.
        /// </summary>
        public static string Finish_this_task {
            get {
                return ResourceManager.GetString("Finish_this_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finished at.
        /// </summary>
        public static string finished_at {
            get {
                return ResourceManager.GetString("finished_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0}.
        /// </summary>
        public static string from_X {
            get {
                return ResourceManager.GetString("from_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string hrs {
            get {
                return ResourceManager.GetString("hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string item_done {
            get {
                return ResourceManager.GetString("item_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        public static string mins {
            get {
                return ResourceManager.GetString("mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) left.
        /// </summary>
        public static string N_days_left {
            get {
                return ResourceManager.GetString("N_days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} planned.
        /// </summary>
        public static string N_planned {
            get {
                return ResourceManager.GetString("N_planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} spent.
        /// </summary>
        public static string N_spent {
            get {
                return ResourceManager.GetString("N_spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New bug.
        /// </summary>
        public static string New_bug {
            get {
                return ResourceManager.GetString("New_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New review.
        /// </summary>
        public static string New_tag {
            get {
                return ResourceManager.GetString("New_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a new review.
        /// </summary>
        public static string New_tag_tooltip {
            get {
                return ResourceManager.GetString("New_tag_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string New_task {
            get {
                return ResourceManager.GetString("New_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task name.
        /// </summary>
        public static string New_task_name {
            get {
                return ResourceManager.GetString("New_task_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no tasks for you..
        /// </summary>
        public static string no_tasks_for_you {
            get {
                return ResourceManager.GetString("no_tasks_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not planned yet.
        /// </summary>
        public static string not_planned {
            get {
                return ResourceManager.GetString("not_planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasting tasks.
        /// </summary>
        public static string Pasting_tasks {
            get {
                return ResourceManager.GetString("Pasting_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to paste {0} tasks at the backlog item {1}.
        ///Are you sure?.
        /// </summary>
        public static string Pasting_tasks_prompt {
            get {
                return ResourceManager.GetString("Pasting_tasks_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable.
        /// </summary>
        public static string Payable {
            get {
                return ResourceManager.GetString("Payable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must join the project first to be able to create tasks.
        /// </summary>
        public static string Please_join_the_project_to_create_the_new_task {
            get {
                return ResourceManager.GetString("Please_join_the_project_to_create_the_new_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to view tasks at list view mode, you need to select a backlog item..
        /// </summary>
        public static string Please_select_a_backlog_item {
            get {
                return ResourceManager.GetString("Please_select_a_backlog_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a backlog item to create the new task.
        /// </summary>
        public static string Please_select_a_backlog_item_to_create_the_new_task {
            get {
                return ResourceManager.GetString("Please_select_a_backlog_item_to_create_the_new_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post it.
        /// </summary>
        public static string Post_it {
            get {
                return ResourceManager.GetString("Post_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press Esc to cancel.
        /// </summary>
        public static string press_Esc_to_cancel {
            get {
                return ResourceManager.GetString("press_Esc_to_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        public static string Real {
            get {
                return ResourceManager.GetString("Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove review tag.
        /// </summary>
        public static string Remove_review_tag {
            get {
                return ResourceManager.GetString("Remove_review_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string Replan_item {
            get {
                return ResourceManager.GetString("Replan_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked replans the backlog item hours according task hours.
        /// </summary>
        public static string Replan_item_tooltip {
            get {
                return ResourceManager.GetString("Replan_item_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review_tag {
            get {
                return ResourceManager.GetString("Review_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Review_tags {
            get {
                return ResourceManager.GetString("Review_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role not defined.
        /// </summary>
        public static string role_not_defined {
            get {
                return ResourceManager.GetString("role_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs.
        /// </summary>
        public static string secs {
            get {
                return ResourceManager.GetString("secs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns on/off the multi-item selection.
        /// </summary>
        public static string Selection_tooltip {
            get {
                return ResourceManager.GetString("Selection_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this task as planned.
        /// </summary>
        public static string Set_this_task_as_planned {
            get {
                return ResourceManager.GetString("Set_this_task_as_planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this task as working on.
        /// </summary>
        public static string Set_this_task_as_working_on {
            get {
                return ResourceManager.GetString("Set_this_task_as_working_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all items.
        /// </summary>
        public static string show_all_items {
            get {
                return ResourceManager.GetString("show_all_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already spent hours.
        /// </summary>
        public static string Spent_hours {
            get {
                return ResourceManager.GetString("Spent_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0: MMM-dd}.
        /// </summary>
        public static string sprintEndDate_filter {
            get {
                return ResourceManager.GetString("sprintEndDate_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0: MMM-dd} to.
        /// </summary>
        public static string sprintStartDate_filter {
            get {
                return ResourceManager.GetString("sprintStartDate_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start clock.
        /// </summary>
        public static string Start_clock {
            get {
                return ResourceManager.GetString("Start_clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start time tracking.
        /// </summary>
        public static string start_track {
            get {
                return ResourceManager.GetString("start_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to start/stop the clock.
        /// </summary>
        public static string startClock_tooltip {
            get {
                return ResourceManager.GetString("startClock_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at.
        /// </summary>
        public static string started_at {
            get {
                return ResourceManager.GetString("started_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review {0}.
        /// </summary>
        public static string TagName_N {
            get {
                return ResourceManager.GetString("TagName_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take one task.
        /// </summary>
        public static string take_one_task {
            get {
                return ResourceManager.GetString("take_one_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0}.
        /// </summary>
        public static string Task_N {
            get {
                return ResourceManager.GetString("Task_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Task_type {
            get {
                return ResourceManager.GetString("Task_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be aware that the planned effort to finish task &apos;{0}&apos; has ran out..
        /// </summary>
        public static string The_planned_effor_to_finish_task_T_has_ran_out {
            get {
                return ResourceManager.GetString("The_planned_effor_to_finish_task_T_has_ran_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time is up.
        /// </summary>
        public static string Time_is_up {
            get {
                return ResourceManager.GetString("Time_is_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to {0}.
        /// </summary>
        public static string to_X {
            get {
                return ResourceManager.GetString("to_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream whistles {
            get {
                return ResourceManager.GetStream("whistles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task to me.
        /// </summary>
        public static string work_on_it {
            get {
                return ResourceManager.GetString("work_on_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working at &apos;{0}&apos;.
        /// </summary>
        public static string Working_at_T {
            get {
                return ResourceManager.GetString("Working_at_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only paste your own tasks.
        /// </summary>
        public static string You_can_only_paste_your_own_tasks {
            get {
                return ResourceManager.GetString("You_can_only_paste_your_own_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a project member to paste tasks.
        /// </summary>
        public static string You_need_to_be_a_project_member_to_paste_tasks {
            get {
                return ResourceManager.GetString("You_need_to_be_a_project_member_to_paste_tasks", resourceCulture);
            }
        }
    }
}
