//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Projects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.Projects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for &quot;{0}&quot;.
        /// </summary>
        public static string _for_X {
            get {
                return ResourceManager.GetString("_for_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  as .
        /// </summary>
        public static string _hrs_as_ {
            get {
                return ResourceManager.GetString("_hrs_as_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actual hours.
        /// </summary>
        public static string actual_hours {
            get {
                return ResourceManager.GetString("actual_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all projects.
        /// </summary>
        public static string ALL_PROJECTS {
            get {
                return ResourceManager.GetString("ALL_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone can join.
        /// </summary>
        public static string Anyone_can_join {
            get {
                return ResourceManager.GetString("Anyone_can_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anytime.
        /// </summary>
        public static string ANYTIME {
            get {
                return ResourceManager.GetString("ANYTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ({0}).
        /// </summary>
        public static string assigned_to {
            get {
                return ResourceManager.GetString("assigned_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to &apos;{0}&apos;.
        /// </summary>
        public static string back_to_project_N {
            get {
                return ResourceManager.GetString("back_to_project_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Scrum Master should be at the project..
        /// </summary>
        public static string BRE_CAN_NOT_REMOVE_LAST_SCRUM_MASTER_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_NOT_REMOVE_LAST_SCRUM_MASTER_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member can not be removed.
        /// </summary>
        public static string BRE_CAN_NOT_REMOVE_LAST_SCRUM_MASTER_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_NOT_REMOVE_LAST_SCRUM_MASTER_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to alloc this resource for this amount of hours.
        ///Try to reduce its allocation time..
        /// </summary>
        public static string BRE_INVALID_MEMBER_WORKLOAD_errorMessage {
            get {
                return ResourceManager.GetString("BRE_INVALID_MEMBER_WORKLOAD_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource allocation not allowed.
        /// </summary>
        public static string BRE_INVALID_MEMBER_WORKLOAD_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_INVALID_MEMBER_WORKLOAD_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The already compromised budget based on the amount of hours that this project team had worked until now..
        /// </summary>
        public static string budgetIndicator_tooltip {
            get {
                return ResourceManager.GetString("budgetIndicator_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with current planning.
        /// </summary>
        public static string C_tooltip {
            get {
                return ResourceManager.GetString("C_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to join this project.
        /// </summary>
        public static string Click_here_to_join_the_project {
            get {
                return ResourceManager.GetString("Click_here_to_join_the_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_project {
            get {
                return ResourceManager.GetString("Close_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to close this project and release all project team.
        ///Are you sure?.
        /// </summary>
        public static string Close_project_message {
            get {
                return ResourceManager.GetString("Close_project_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to close this project and release all project team.
        ///There are unfinished items, do you want to close them? .
        /// </summary>
        public static string Close_project_message_close_items {
            get {
                return ResourceManager.GetString("Close_project_message_close_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed projects.
        /// </summary>
        public static string CLOSED_PROJECTS {
            get {
                return ResourceManager.GetString("CLOSED_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code repo.
        /// </summary>
        public static string Code_rep {
            get {
                return ResourceManager.GetString("Code_rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code repository path.
        /// </summary>
        public static string Code_repository_path {
            get {
                return ResourceManager.GetString("Code_repository_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan {0}.
        /// </summary>
        public static string comparing_with_N {
            get {
                return ResourceManager.GetString("comparing_with_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proposal.
        /// </summary>
        public static string comparing_with_proposal {
            get {
                return ResourceManager.GetString("comparing_with_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy list.
        /// </summary>
        public static string Copy_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open path &apos;{0}&apos;..
        /// </summary>
        public static string Could_not_open_path_N {
            get {
                return ResourceManager.GetString("Could_not_open_path_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new one at.
        /// </summary>
        public static string create_a_new_one {
            get {
                return ResourceManager.GetString("create_a_new_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} repo.
        /// </summary>
        public static string Create_N_repository {
            get {
                return ResourceManager.GetString("Create_N_repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string Create_new_project {
            get {
                return ResourceManager.GetString("Create_new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a repository or choose to create a new one..
        /// </summary>
        public static string Create_rep_text_help {
            get {
                return ResourceManager.GetString("Create_rep_text_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &apos;{0}&apos; has been sucessfully created..
        /// </summary>
        public static string CreateProjectSuccessMessage {
            get {
                return ResourceManager.GetString("CreateProjectSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MMM.
        /// </summary>
        public static string dd_MMM {
            get {
                return ResourceManager.GetString("dd_MMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do not use as baseline.
        /// </summary>
        public static string do_not_use_as_baseline {
            get {
                return ResourceManager.GetString("do_not_use_as_baseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project folder.
        /// </summary>
        public static string Doc_rep {
            get {
                return ResourceManager.GetString("Doc_rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project folder.
        /// </summary>
        public static string Doc_repository_path {
            get {
                return ResourceManager.GetString("Doc_repository_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External command.
        /// </summary>
        public static string External_command {
            get {
                return ResourceManager.GetString("External_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocured when trying to run the external command.
        ///Check your external command definition..
        /// </summary>
        public static string External_command_error {
            get {
                return ResourceManager.GetString("External_command_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the external program path that should be used to open repository logs.
        ///Ex: C:\Program Files\TortoiseSVN\bin\TortoiseProc.exe /command:log /path:&quot;{0}&quot; /findstring:&quot;{1}&quot; /findtype:1.
        /// </summary>
        public static string External_command_tooltip {
            get {
                return ResourceManager.GetString("External_command_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1o.
        /// </summary>
        public static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with first planning.
        /// </summary>
        public static string F_tooltip {
            get {
                return ResourceManager.GetString("F_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five years ago.
        /// </summary>
        public static string FIVE_YEARS_AGO {
            get {
                return ResourceManager.GetString("FIVE_YEARS_AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu projeto ainda não possui itens de backlog planejados.&lt;LineBreak/&gt;Clique na aba &lt;Bold&gt;Backlog&lt;/Bold&gt; para adicionar itens e planejá-los..
        /// </summary>
        public static string HELP_Items_not_planned {
            get {
                return ResourceManager.GetString("HELP_Items_not_planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu projeto ainda não possui nenhuma proposta comercial aprovada.&lt;LineBreak/&gt;Clique na aba &lt;Bold&gt;Propostas&lt;/Bold&gt; parar criar propostas e aprová-las.&lt;LineBreak/&gt;Caso não necessite de uma proposta comercial, você pode iniciar o projeto clicando no botão &lt;Bold&gt;Iniciar&lt;/Bold&gt; no topo da tela..
        /// </summary>
        public static string HELP_no_proposal {
            get {
                return ResourceManager.GetString("HELP_no_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBlock TextWrapping=&quot;Wrap&quot;&gt;
        ///                    Congratulations,&lt;LineBreak/&gt;
        ///                    your Project has been created.&lt;LineBreak/&gt;&lt;LineBreak/&gt;
        ///                    
        ///You can use the &lt;Bold&gt;Backlog&lt;/Bold&gt; tab to add Project items. To estimate the effort for each item, just click over the item and provide the amount of estimated hours to finish the item.&lt;LineBreak/&gt;
        ///                    These hours will be used at the project burndown chart.&lt;LineBreak/&gt;&lt;LineBreak/&gt;
        ///                     After th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HELP_Project_created {
            get {
                return ResourceManager.GetString("HELP_Project_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs ahead.
        /// </summary>
        public static string hrs_ahead {
            get {
                return ResourceManager.GetString("hrs_ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs behind.
        /// </summary>
        public static string hrs_behind {
            get {
                return ResourceManager.GetString("hrs_behind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i am committed.
        /// </summary>
        public static string im_envolved {
            get {
                return ResourceManager.GetString("im_envolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important dates.
        /// </summary>
        public static string Important_dates {
            get {
                return ResourceManager.GetString("Important_dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My day.
        /// </summary>
        public static string My_day {
            get {
                return ResourceManager.GetString("My_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Engagement.
        /// </summary>
        public static string My_engagement {
            get {
                return ResourceManager.GetString("My_engagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My observer tasks.
        /// </summary>
        public static string My_observer_tasks {
            get {
                return ResourceManager.GetString("My_observer_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My projects.
        /// </summary>
        public static string My_projects {
            get {
                return ResourceManager.GetString("My_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tasks.
        /// </summary>
        public static string My_tasks {
            get {
                return ResourceManager.GetString("My_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s).
        /// </summary>
        public static string N_days {
            get {
                return ResourceManager.GetString("N_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) to sprint {1} end, of {2} sprints.
        /// </summary>
        public static string N_days_to_end_sprint_N_of_N {
            get {
                return ResourceManager.GetString("N_days_to_end_sprint_N_of_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} hrs.
        /// </summary>
        public static string N_hrs {
            get {
                return ResourceManager.GetString("N_hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} worked hours.
        /// </summary>
        public static string N_worked_hours {
            get {
                return ResourceManager.GetString("N_worked_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to need help?.
        /// </summary>
        public static string need_help {
            get {
                return ResourceManager.GetString("need_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string New_project {
            get {
                return ResourceManager.GetString("New_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no items.
        /// </summary>
        public static string no_items {
            get {
                return ResourceManager.GetString("no_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects were found..
        /// </summary>
        public static string No_projects_were_found {
            get {
                return ResourceManager.GetString("No_projects_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to type a project name, number ou client name at the search text box..
        /// </summary>
        public static string No_projects_were_found_tip {
            get {
                return ResourceManager.GetString("No_projects_were_found_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok, i got it.
        /// </summary>
        public static string ok_i_know {
            get {
                return ResourceManager.GetString("ok_i_know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one year ago.
        /// </summary>
        public static string ONE_YEAR_AGO {
            get {
                return ResourceManager.GetString("ONE_YEAR_AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open projects.
        /// </summary>
        public static string OPEN_PROJECTS {
            get {
                return ResourceManager.GetString("OPEN_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opportunities.
        /// </summary>
        public static string OPPORTUNITIES_PROJECTS {
            get {
                return ResourceManager.GetString("OPPORTUNITIES_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with proposal planning.
        /// </summary>
        public static string P_tooltip {
            get {
                return ResourceManager.GetString("P_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planned.
        /// </summary>
        public static string planned {
            get {
                return ResourceManager.GetString("planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planned hours.
        /// </summary>
        public static string Planned_hours {
            get {
                return ResourceManager.GetString("Planned_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planned hours to finish project.
        /// </summary>
        public static string planned_hours_to_finish_the_project {
            get {
                return ResourceManager.GetString("planned_hours_to_finish_the_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned start date.
        /// </summary>
        public static string Planned_start_date {
            get {
                return ResourceManager.GetString("Planned_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project end.
        /// </summary>
        public static string PProject_end {
            get {
                return ResourceManager.GetString("PProject_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define and prioriza the backlog..
        /// </summary>
        public static string Product_Owner_description {
            get {
                return ResourceManager.GetString("Product_Owner_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Owner.
        /// </summary>
        public static string Product_Owner_Role {
            get {
                return ResourceManager.GetString("Product_Owner_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O..
        /// </summary>
        public static string Product_Owner_Role_SN {
            get {
                return ResourceManager.GetString("Product_Owner_Role_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project abstract.
        /// </summary>
        public static string Project_abstract {
            get {
                return ResourceManager.GetString("Project_abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Burndown.
        /// </summary>
        public static string Project_Burndown {
            get {
                return ResourceManager.GetString("Project_Burndown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project created.
        /// </summary>
        public static string Project_created {
            get {
                return ResourceManager.GetString("Project_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project details.
        /// </summary>
        public static string Project_details {
            get {
                return ResourceManager.GetString("Project_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string Project_details1 {
            get {
                return ResourceManager.GetString("Project_details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project end.
        /// </summary>
        public static string project_end {
            get {
                return ResourceManager.GetString("project_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project expired.
        /// </summary>
        public static string Project_expired {
            get {
                return ResourceManager.GetString("Project_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project finished.
        /// </summary>
        public static string Project_finished {
            get {
                return ResourceManager.GetString("Project_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project guide.
        /// </summary>
        public static string Project_guide_report {
            get {
                return ResourceManager.GetString("Project_guide_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent hours.
        /// </summary>
        public static string Project_Hours_graph {
            get {
                return ResourceManager.GetString("Project_Hours_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators.
        /// </summary>
        public static string Project_indicators_report {
            get {
                return ResourceManager.GetString("Project_indicators_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string Project_name {
            get {
                return ResourceManager.GetString("Project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not started.
        /// </summary>
        public static string Project_not_started {
            get {
                return ResourceManager.GetString("Project_not_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project_number {
            get {
                return ResourceManager.GetString("Project_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope list.
        /// </summary>
        public static string Project_scope_report {
            get {
                return ResourceManager.GetString("Project_scope_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project start.
        /// </summary>
        public static string Project_start {
            get {
                return ResourceManager.GetString("Project_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pts/hrs.
        /// </summary>
        public static string pts_hrs {
            get {
                return ResourceManager.GetString("pts_hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amout of hours that this team have spend correcting bugs..
        /// </summary>
        public static string qualityIndicator_tooltip {
            get {
                return ResourceManager.GetString("qualityIndicator_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % re-work.
        /// </summary>
        public static string re_work {
            get {
                return ResourceManager.GetString("re_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository log settings.
        /// </summary>
        public static string Repository_log_settings {
            get {
                return ResourceManager.GetString("Repository_log_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for &quot;{0}&quot;.
        /// </summary>
        public static string Results_for_X_projects {
            get {
                return ResourceManager.GetString("Results_for_X_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review report.
        /// </summary>
        public static string Review_report {
            get {
                return ResourceManager.GetString("Review_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Master.
        /// </summary>
        public static string Scrum_Master {
            get {
                return ResourceManager.GetString("Scrum_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Master.
        /// </summary>
        public static string Scrum_Master_Role {
            get {
                return ResourceManager.GetString("Scrum_Master_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the project team and remove the impediments..
        /// </summary>
        public static string Scrum_Master_Role_description {
            get {
                return ResourceManager.GetString("Scrum_Master_Role_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.M..
        /// </summary>
        public static string Scrum_Master_Role_SN {
            get {
                return ResourceManager.GetString("Scrum_Master_Role_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify team.
        /// </summary>
        public static string Send_Mail {
            get {
                return ResourceManager.GetString("Send_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since {0}.
        /// </summary>
        public static string since_N {
            get {
                return ResourceManager.GetString("since_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint 1 has not started yet.
        /// </summary>
        public static string Sprint_1_not_started_yet {
            get {
                return ResourceManager.GetString("Sprint_1_not_started_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprint {0}.
        /// </summary>
        public static string sprint_N {
            get {
                return ResourceManager.GetString("sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint {0} start.
        /// </summary>
        public static string Sprint_N_start {
            get {
                return ResourceManager.GetString("Sprint_N_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint review.
        /// </summary>
        public static string Sprint_review {
            get {
                return ResourceManager.GetString("Sprint_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start project.
        /// </summary>
        public static string Start_project {
            get {
                return ResourceManager.GetString("Start_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to start this project.
        ///Are you sure?.
        /// </summary>
        public static string Start_project_message {
            get {
                return ResourceManager.GetString("Start_project_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to start this project.
        ///This first sprint of this project was planned to start at {0:d}.
        ///Do you want to start it moving changing the sprint start date to today?.
        /// </summary>
        public static string Start_project_message_move_date {
            get {
                return ResourceManager.GetString("Start_project_message_move_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team_Role {
            get {
                return ResourceManager.GetString("Team_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General developers..
        /// </summary>
        public static string Team_Role_description {
            get {
                return ResourceManager.GetString("Team_Role_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM.
        /// </summary>
        public static string Team_Role_SN {
            get {
                return ResourceManager.GetString("Team_Role_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticket project.
        /// </summary>
        public static string ticket_project {
            get {
                return ResourceManager.GetString("ticket_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket projects do not have sprints. Instead, they have a continuous backlog that is prioritized and delivered as the client requests..
        /// </summary>
        public static string Ticket_project_alert {
            get {
                return ResourceManager.GetString("Ticket_project_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked {0} hours in this project.
        /// </summary>
        public static string Total_Hours_In_This_Project {
            get {
                return ResourceManager.GetString("Total_Hours_In_This_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two years ago.
        /// </summary>
        public static string TWO_YEARS_AGO {
            get {
                return ResourceManager.GetString("TWO_YEARS_AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use as baseline.
        /// </summary>
        public static string use_as_baseline {
            get {
                return ResourceManager.GetString("use_as_baseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use last project as model.
        /// </summary>
        public static string use_last_project_as_model {
            get {
                return ResourceManager.GetString("use_last_project_as_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use the same from this project.
        /// </summary>
        public static string use_old_one {
            get {
                return ResourceManager.GetString("use_old_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use one of the following code repositories.
        /// </summary>
        public static string use_one_of_the_following_reps {
            get {
                return ResourceManager.GetString("use_one_of_the_following_reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % used budget.
        /// </summary>
        public static string used_budget {
            get {
                return ResourceManager.GetString("used_budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of hours that this project team takes to finish 1 backlog item point.
        ///The factory average is {0:0.0} points per hour..
        /// </summary>
        public static string velocityIndicator_tooltip {
            get {
                return ResourceManager.GetString("velocityIndicator_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View project team.
        /// </summary>
        public static string View_other_members {
            get {
                return ResourceManager.GetString("View_other_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % walked.
        /// </summary>
        public static string walked {
            get {
                return ResourceManager.GetString("walked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worked.
        /// </summary>
        public static string worked {
            get {
                return ResourceManager.GetString("worked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worked hours.
        /// </summary>
        public static string Worked_hours {
            get {
                return ResourceManager.GetString("Worked_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not member of this project team..
        /// </summary>
        public static string You_are_not_in_this_project_team {
            get {
                return ResourceManager.GetString("You_are_not_in_this_project_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ZoomLevel_Items {
            get {
                return ResourceManager.GetString("ZoomLevel_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ZoomLevel_Project {
            get {
                return ResourceManager.GetString("ZoomLevel_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string ZoomLevel_Roles {
            get {
                return ResourceManager.GetString("ZoomLevel_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        public static string ZoomLevel_Structures {
            get {
                return ResourceManager.GetString("ZoomLevel_Structures", resourceCulture);
            }
        }
    }
}
