//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Login.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.Login.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authenticate at {0}.
        /// </summary>
        public static string authenticate_at_P {
            get {
                return ResourceManager.GetString("authenticate_at_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate with.
        /// </summary>
        public static string Authenticate_with {
            get {
                return ResourceManager.GetString("Authenticate_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; authentication is not supported by the server &apos;{1}&apos;..
        /// </summary>
        public static string Authorization_provider_not_supported {
            get {
                return ResourceManager.GetString("Authorization_provider_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password, or could not get response from {0}..
        /// </summary>
        public static string bad_login {
            get {
                return ResourceManager.GetString("bad_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change server.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for help..
        /// </summary>
        public static string Click_here_for_help {
            get {
                return ResourceManager.GetString("Click_here_for_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to login at a corporate server, click here..
        /// </summary>
        public static string Click_here_to_use_a_corporate_server {
            get {
                return ResourceManager.GetString("Click_here_to_use_a_corporate_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to conect at our public server..
        /// </summary>
        public static string Click_here_to_use_the_demo_server {
            get {
                return ResourceManager.GetString("Click_here_to_use_the_demo_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect at server.
        /// </summary>
        public static string Connect_at_server {
            get {
                return ResourceManager.GetString("Connect_at_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on authorization provider connection. Check log file for detailed information..
        /// </summary>
        public static string Error_on_provider {
            get {
                return ResourceManager.GetString("Error_on_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scrum Factory server could not validate credentials against the autheticator provider..
        /// </summary>
        public static string Factory_could_not_validate_credentials {
            get {
                return ResourceManager.GetString("Factory_could_not_validate_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could be an internal error on the server-side, a database connection problem or a proxy issue on the server-side..
        /// </summary>
        public static string Factory_signin_error {
            get {
                return ResourceManager.GetString("Factory_signin_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        public static string Invalid_credentials {
            get {
                return ResourceManager.GetString("Invalid_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having a hard time trying to singing?.
        /// </summary>
        public static string login_help {
            get {
                return ResourceManager.GetString("login_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sign In REST url was not found at the server.
        ///If your client version is 2.50.*.* or higher make sure your Server DLLs are updated.
        ///You can download the latest server dlls at http://thescrumfactory2012.codeplex.com/releases..
        /// </summary>
        public static string Login_method_not_found {
            get {
                return ResourceManager.GetString("Login_method_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your client version is not updated and can not work with this server.
        ///Close the application and start it again to automticallu upgrade your client version.
        /// </summary>
        public static string old_client_version_message {
            get {
                return ResourceManager.GetString("old_client_version_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scrum Factory Server Version is too old to work with this client.
        ///Please ask your server administrator to download at install the new server version from www.scrum-factory.com..
        /// </summary>
        public static string old_server_version_message {
            get {
                return ResourceManager.GetString("old_server_version_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public hub server.
        /// </summary>
        public static string Public_hub_server {
            get {
                return ResourceManager.GetString("Public_hub_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our public server, where anyone can access it..
        /// </summary>
        public static string Public_hub_server_tooltip {
            get {
                return ResourceManager.GetString("Public_hub_server_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/ErrorStatus/errorSecurity.png.
        /// </summary>
        public static string ScrumFactory_Exceptions_ForbittenException_errorImageSource {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ForbittenException_errorImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not authorized to perform this operation..
        /// </summary>
        public static string ScrumFactory_Exceptions_ForbittenException_errorMessage {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ForbittenException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        public static string ScrumFactory_Exceptions_ForbittenException_errorMessageTitle {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ForbittenException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/ErrorStatus/errorNetWork.png.
        /// </summary>
        public static string ScrumFactory_Exceptions_NetworkException_errorImageSource {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_NetworkException_errorImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the Factory Server.
        ///Verify your network connection..
        /// </summary>
        public static string ScrumFactory_Exceptions_NetworkException_errorMessage {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_NetworkException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the server.
        /// </summary>
        public static string ScrumFactory_Exceptions_NetworkException_errorMessageTitle {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_NetworkException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/ErrorStatus/errorServer.png.
        /// </summary>
        public static string ScrumFactory_Exceptions_ServerErrorException_errorImageSource {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ServerErrorException_errorImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error ocurred at the Factory Server..
        /// </summary>
        public static string ScrumFactory_Exceptions_ServerErrorException_errorMessage {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ServerErrorException_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string ScrumFactory_Exceptions_ServerErrorException_errorMessageTitle {
            get {
                return ResourceManager.GetString("ScrumFactory_Exceptions_ServerErrorException_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not keep any of your sensitive data.
        ///Your password is send using secure channel directly to the authentication provider..
        /// </summary>
        public static string secure_tooltip {
            get {
                return ResourceManager.GetString("secure_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a server to login.
        /// </summary>
        public static string Select_a_server_to_login {
            get {
                return ResourceManager.GetString("Select_a_server_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select authenticaton method to connect at.
        /// </summary>
        public static string Select_authenticaton_to_connect_at {
            get {
                return ResourceManager.GetString("Select_authenticaton_to_connect_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server address.
        /// </summary>
        public static string server_address {
            get {
                return ResourceManager.GetString("server_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how do you want to sign in to Scrum Factory.
        /// </summary>
        public static string Sign_in_using {
            get {
                return ResourceManager.GetString("Sign_in_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing....
        /// </summary>
        public static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand alone server (beta).
        /// </summary>
        public static string Stand_alone_server {
            get {
                return ResourceManager.GetString("Stand_alone_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It runs on your computer, and only you can access it. No internet server, or database service is required..
        /// </summary>
        public static string Stand_alone_server_tooltip {
            get {
                return ResourceManager.GetString("Stand_alone_server_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user is blocked by the factory administrator..
        /// </summary>
        public static string user_blocked_message {
            get {
                return ResourceManager.GetString("user_blocked_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are connecting at a corporate server: {0}.
        /// </summary>
        public static string You_are_connecting_at_a_corporate_server_N {
            get {
                return ResourceManager.GetString("You_are_connecting_at_a_corporate_server_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your company server.
        /// </summary>
        public static string Your_company_server {
            get {
                return ResourceManager.GetString("Your_company_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Scrum Factory server installed inside your company where all your developers, and only them can access it..
        /// </summary>
        public static string Your_company_server_tooltip {
            get {
                return ResourceManager.GetString("Your_company_server_tooltip", resourceCulture);
            }
        }
    }
}
