//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Proposals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.Proposals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New proposal.
        /// </summary>
        public static string Add_proposal {
            get {
                return ResourceManager.GetString("Add_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when reading this proposal.
        /// </summary>
        public static string An_error_occured_when_reading_this_proposal {
            get {
                return ResourceManager.GetString("An_error_occured_when_reading_this_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve proposal.
        /// </summary>
        public static string Approve_proposal {
            get {
                return ResourceManager.GetString("Approve_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you approve this proposal you will not be able to change it.
        ///Are you sure you want to approve it?.
        /// </summary>
        public static string Approve_proposal_tip {
            get {
                return ResourceManager.GetString("Approve_proposal_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0}.
        /// </summary>
        public static string at_D {
            get {
                return ResourceManager.GetString("at_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , by {0}.
        /// </summary>
        public static string by_W {
            get {
                return ResourceManager.GetString("by_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to see proposals values you should have special permissions.
        ///Please, contact the Factory Owner to request those permissions..
        /// </summary>
        public static string Can_not_see_proposal_message {
            get {
                return ResourceManager.GetString("Can_not_see_proposal_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to see project proposals.
        /// </summary>
        public static string Can_not_see_proposal_title {
            get {
                return ResourceManager.GetString("Can_not_see_proposal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client cost.
        /// </summary>
        public static string Client_cost {
            get {
                return ResourceManager.GetString("Client_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs.
        /// </summary>
        public static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string Down_clause {
            get {
                return ResourceManager.GetString("Down_clause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading proposal.
        /// </summary>
        public static string Error_reading_proposal {
            get {
                return ResourceManager.GetString("Error_reading_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final price.
        /// </summary>
        public static string Final_price {
            get {
                return ResourceManager.GetString("Final_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed costs.
        /// </summary>
        public static string Fixed_costs {
            get {
                return ResourceManager.GetString("Fixed_costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour costs.
        /// </summary>
        public static string Hour_costs {
            get {
                return ResourceManager.GetString("Hour_costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items price.
        /// </summary>
        public static string Items_price {
            get {
                return ResourceManager.GetString("Items_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New clause.
        /// </summary>
        public static string New_clause {
            get {
                return ResourceManager.GetString("New_clause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cost.
        /// </summary>
        public static string New_cost {
            get {
                return ResourceManager.GetString("New_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New proposal.
        /// </summary>
        public static string New_proposal {
            get {
                return ResourceManager.GetString("New_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should have at least one proposal to edit its hour costs..
        /// </summary>
        public static string No_proposals_tooltip {
            get {
                return ResourceManager.GetString("No_proposals_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview proposal.
        /// </summary>
        public static string Preview_proposal {
            get {
                return ResourceManager.GetString("Preview_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview proposal &apos;{0}&apos;.
        /// </summary>
        public static string Preview_proposal_N {
            get {
                return ResourceManager.GetString("Preview_proposal_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        public static string Proposal {
            get {
                return ResourceManager.GetString("Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clauses.
        /// </summary>
        public static string Proposal_clauses {
            get {
                return ResourceManager.GetString("Proposal_clauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed costs.
        /// </summary>
        public static string Proposal_fixed_costs {
            get {
                return ResourceManager.GetString("Proposal_fixed_costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal items.
        /// </summary>
        public static string Proposal_items {
            get {
                return ResourceManager.GetString("Proposal_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposals.
        /// </summary>
        public static string Proposals {
            get {
                return ResourceManager.GetString("Proposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposals list.
        /// </summary>
        public static string Proposals_list {
            get {
                return ResourceManager.GetString("Proposals_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject proposal.
        /// </summary>
        public static string Reject_proposal {
            get {
                return ResourceManager.GetString("Reject_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you reject this proposal you will not be able to change it.
        ///Are you sure you want to reject it?.
        /// </summary>
        public static string Reject_proposal_tip {
            get {
                return ResourceManager.GetString("Reject_proposal_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show proposals.
        /// </summary>
        public static string show_hide {
            get {
                return ResourceManager.GetString("show_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to show this project proposals, please click at the &quot;Show proposals&quot; button..
        /// </summary>
        public static string show_hide_tip {
            get {
                return ResourceManager.GetString("show_hide_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with sprint dates.
        /// </summary>
        public static string Sync_with_sprint_dates {
            get {
                return ResourceManager.GetString("Sync_with_sprint_dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string Up_clause {
            get {
                return ResourceManager.GetString("Up_clause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other currency.
        /// </summary>
        public static string use_another_currency {
            get {
                return ResourceManager.GetString("use_another_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use calculated price.
        /// </summary>
        public static string use_calc_price {
            get {
                return ResourceManager.GetString("use_calc_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
