//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Team.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumFactory.Team.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for &quot;{0}&quot;.
        /// </summary>
        public static string _for_X {
            get {
                return ResourceManager.GetString("_for_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1/4 of day free.
        /// </summary>
        public static string A_3QUARTER_BUSY {
            get {
                return ResourceManager.GetString("A_3QUARTER_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 3/4 of day free.
        /// </summary>
        public static string A_QUARTER_BUSY {
            get {
                return ResourceManager.GetString("A_QUARTER_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member.
        /// </summary>
        public static string Add_member {
            get {
                return ResourceManager.GetString("Add_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string Add_member_as {
            get {
                return ResourceManager.GetString("Add_member_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New contact.
        /// </summary>
        public static string Add_new_contact {
            get {
                return ResourceManager.GetString("Add_new_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New role.
        /// </summary>
        public static string Add_new_role {
            get {
                return ResourceManager.GetString("Add_new_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_to_project {
            get {
                return ResourceManager.GetString("Add_to_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new {0}.
        /// </summary>
        public static string Adding_new_ROLE {
            get {
                return ResourceManager.GetString("Adding_new_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        public static string Allocation {
            get {
                return ResourceManager.GetString("Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much of your day you will dedicate to this project.
        /// </summary>
        public static string Allocation_LABELHELP {
            get {
                return ResourceManager.GetString("Allocation_LABELHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and more....
        /// </summary>
        public static string and_more {
            get {
                return ResourceManager.GetString("and_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As.
        /// </summary>
        public static string As {
            get {
                return ResourceManager.GetString("As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your role at this project.
        /// </summary>
        public static string As_LABELHELP {
            get {
                return ResourceManager.GetString("As_LABELHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ({0}).
        /// </summary>
        public static string assigned_to {
            get {
                return ResourceManager.GetString("assigned_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late or already finished items can not be moved to other sprint..
        /// </summary>
        public static string BRE_CAN_CHANGE_PRIORITY_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_CHANGE_PRIORITY_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change item priority.
        /// </summary>
        public static string BRE_CAN_CHANGE_PRIORITY_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_CHANGE_PRIORITY_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory should have at least one Factory Owner..
        /// </summary>
        public static string BRE_CAN_NOT_REMOVE_LAST_FACTORY_OWNER_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_NOT_REMOVE_LAST_FACTORY_OWNER_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change factory owner.
        /// </summary>
        public static string BRE_CAN_NOT_REMOVE_LAST_FACTORY_OWNER_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_NOT_REMOVE_LAST_FACTORY_OWNER_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Scrum Master should be at the project..
        /// </summary>
        public static string BRE_CAN_NOT_REMOVE_LAST_SCRUM_MASTER_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_NOT_REMOVE_LAST_SCRUM_MASTER_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member can not be removed.
        /// </summary>
        public static string BRE_CAN_NOT_REMOVE_LAST_SCRUM_MASTER_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_NOT_REMOVE_LAST_SCRUM_MASTER_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This member has already worked at tasks in this project.
        ///If he is no longer working at the project, you can inativate him..
        /// </summary>
        public static string BRE_CAN_NOT_REMOVE_MEMBER_WITH_TASKS_errorMessage {
            get {
                return ResourceManager.GetString("BRE_CAN_NOT_REMOVE_MEMBER_WITH_TASKS_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member can not be removed.
        /// </summary>
        public static string BRE_CAN_NOT_REMOVE_MEMBER_WITH_TASKS_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_CAN_NOT_REMOVE_MEMBER_WITH_TASKS_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to alloc this resource for this amount of hours.
        ///Try to reduce its allocation time..
        /// </summary>
        public static string BRE_INVALID_MEMBER_WORKLOAD_errorMessage {
            get {
                return ResourceManager.GetString("BRE_INVALID_MEMBER_WORKLOAD_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource allocation not allowed.
        /// </summary>
        public static string BRE_INVALID_MEMBER_WORKLOAD_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_INVALID_MEMBER_WORKLOAD_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles can not be removed when the project already has items planned for them.
        ///In order to remove this role, try to clear all hours planned for it..
        /// </summary>
        public static string BRE_ROLE_ALREADY_PLANNED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_ROLE_ALREADY_PLANNED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role can not be removed.
        /// </summary>
        public static string BRE_ROLE_ALREADY_PLANNED_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_ROLE_ALREADY_PLANNED_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is already used by a project member..
        /// </summary>
        public static string BRE_ROLE_ALREADY_USED_errorMessage {
            get {
                return ResourceManager.GetString("BRE_ROLE_ALREADY_USED_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role can not be removed.
        /// </summary>
        public static string BRE_ROLE_ALREADY_USED_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_ROLE_ALREADY_USED_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Scrum Master Role is necessary at the project..
        /// </summary>
        public static string BRE_SCRUM_MASTER_ROLE_IS_NECESSARY_errorMessage {
            get {
                return ResourceManager.GetString("BRE_SCRUM_MASTER_ROLE_IS_NECESSARY_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role can not be removed or changed.
        /// </summary>
        public static string BRE_SCRUM_MASTER_ROLE_IS_NECESSARY_errorMessageTitle {
            get {
                return ResourceManager.GetString("BRE_SCRUM_MASTER_ROLE_IS_NECESSARY_errorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solved your first bug.
        /// </summary>
        public static string Bug_killer_description {
            get {
                return ResourceManager.GetString("Bug_killer_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know what to do.
        /// </summary>
        public static string Bug_killer_name {
            get {
                return ResourceManager.GetString("Bug_killer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bugs solved (month).
        /// </summary>
        public static string Bugs_Resolved {
            get {
                return ResourceManager.GetString("Bugs_Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can see proposals.
        /// </summary>
        public static string can_see_proposals {
            get {
                return ResourceManager.GetString("can_see_proposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change image.
        /// </summary>
        public static string Change_image {
            get {
                return ResourceManager.GetString("Change_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload an image, or click here to create a Gravatar..
        /// </summary>
        public static string Change_image_tooltip {
            get {
                return ResourceManager.GetString("Change_image_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change you team configuration at the Team Code setting at your profile..
        /// </summary>
        public static string Change_your_team_tooltip {
            get {
                return ResourceManager.GetString("Change_your_team_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact data.
        /// </summary>
        public static string Contact_data {
            get {
                return ResourceManager.GetString("Contact_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string Contact_information {
            get {
                return ResourceManager.GetString("Contact_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s contacts.
        /// </summary>
        public static string Contacts_from_N {
            get {
                return ResourceManager.GetString("Contacts_from_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by {0}.
        /// </summary>
        public static string created_by_N {
            get {
                return ResourceManager.GetString("created_by_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default role.
        /// </summary>
        public static string Default_role {
            get {
                return ResourceManager.GetString("Default_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check as default if you want this role to be used for no-assigned tasks.
        /// </summary>
        public static string Default_role_tooltip {
            get {
                return ResourceManager.GetString("Default_role_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 10 tasks done before planned hours.
        /// </summary>
        public static string Done_before_plannedHours_description {
            get {
                return ResourceManager.GetString("Done_before_plannedHours_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already did.
        /// </summary>
        public static string Done_before_plannedHours_name {
            get {
                return ResourceManager.GetString("Done_before_plannedHours_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        public static string Email_address {
            get {
                return ResourceManager.GetString("Email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engage.
        /// </summary>
        public static string Engage {
            get {
                return ResourceManager.GetString("Engage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        public static string engaged_as {
            get {
                return ResourceManager.GetString("engaged_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at project .
        /// </summary>
        public static string engaged_at_project {
            get {
                return ResourceManager.GetString("engaged_at_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform the amount of hours per day that you can be engaged at each project..
        /// </summary>
        public static string engaged_tooltip {
            get {
                return ResourceManager.GetString("engaged_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory owners.
        /// </summary>
        public static string Factory_owners {
            get {
                return ResourceManager.GetString("Factory_owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Improviment done.
        /// </summary>
        public static string first_improviments_done_description {
            get {
                return ResourceManager.GetString("first_improviments_done_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One improviment done.
        /// </summary>
        public static string first_improviments_done_name {
            get {
                return ResourceManager.GetString("first_improviments_done_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even busy.
        /// </summary>
        public static string FULL_DAY_BUSY {
            get {
                return ResourceManager.GetString("FULL_DAY_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day free.
        /// </summary>
        public static string FULL_DAY_FREE {
            get {
                return ResourceManager.GetString("FULL_DAY_FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Full_name {
            get {
                return ResourceManager.GetString("Full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1/2 of day free.
        /// </summary>
        public static string HALF_DAY_BUSY {
            get {
                return ResourceManager.GetString("HALF_DAY_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important dates.
        /// </summary>
        public static string Important_dates {
            get {
                return ResourceManager.GetString("Important_dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} improvements done (month).
        /// </summary>
        public static string Improvements_Done {
            get {
                return ResourceManager.GetString("Improvements_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is owner.
        /// </summary>
        public static string is_owner {
            get {
                return ResourceManager.GetString("is_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to join this project.
        /// </summary>
        public static string Join_this_project {
            get {
                return ResourceManager.GetString("Join_this_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s engagements.
        /// </summary>
        public static string M_engagement {
            get {
                return ResourceManager.GetString("M_engagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}´s tasks.
        /// </summary>
        public static string M_tasks {
            get {
                return ResourceManager.GetString("M_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member added.
        /// </summary>
        public static string Member_added {
            get {
                return ResourceManager.GetString("Member_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to availability.
        /// </summary>
        public static string Member_work_load {
            get {
                return ResourceManager.GetString("Member_work_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 1000 tasks done.
        /// </summary>
        public static string more_than_1000_tasks_description {
            get {
                return ResourceManager.GetString("more_than_1000_tasks_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string more_than_1000_tasks_name {
            get {
                return ResourceManager.GetString("more_than_1000_tasks_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My company.
        /// </summary>
        public static string My_company {
            get {
                return ResourceManager.GetString("My_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My day.
        /// </summary>
        public static string My_day {
            get {
                return ResourceManager.GetString("My_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My e-mail account.
        /// </summary>
        public static string My_email {
            get {
                return ResourceManager.GetString("My_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My engagement.
        /// </summary>
        public static string My_Engagement {
            get {
                return ResourceManager.GetString("My_Engagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name.
        /// </summary>
        public static string My_name {
            get {
                return ResourceManager.GetString("My_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My team tasks.
        /// </summary>
        public static string My_observer_tasks {
            get {
                return ResourceManager.GetString("My_observer_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string My_profile {
            get {
                return ResourceManager.GetString("My_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My skills.
        /// </summary>
        public static string My_skills {
            get {
                return ResourceManager.GetString("My_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tasks.
        /// </summary>
        public static string My_tasks {
            get {
                return ResourceManager.GetString("My_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s).
        /// </summary>
        public static string N_days {
            get {
                return ResourceManager.GetString("N_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} hrs).
        /// </summary>
        public static string N_hours {
            get {
                return ResourceManager.GetString("N_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours left.
        /// </summary>
        public static string N_hours_left {
            get {
                return ResourceManager.GetString("N_hours_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} hrs of work to do.
        /// </summary>
        public static string N_hours_of_work {
            get {
                return ResourceManager.GetString("N_hours_of_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} people were found.
        /// </summary>
        public static string n_people_were_found {
            get {
                return ResourceManager.GetString("n_people_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} worked hours.
        /// </summary>
        public static string N_worked_hours {
            get {
                return ResourceManager.GetString("N_worked_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or qualification.
        /// </summary>
        public static string Name_or_qualification {
            get {
                return ResourceManager.GetString("Name_or_qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New contact.
        /// </summary>
        public static string New_contact {
            get {
                return ResourceManager.GetString("New_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New role name.
        /// </summary>
        public static string New_role_name {
            get {
                return ResourceManager.GetString("New_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM.
        /// </summary>
        public static string New_role_short_name {
            get {
                return ResourceManager.GetString("New_role_short_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no items.
        /// </summary>
        public static string no_items {
            get {
                return ResourceManager.GetString("no_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resources were found..
        /// </summary>
        public static string No_items_were_found {
            get {
                return ResourceManager.GetString("No_items_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to change the workload filter..
        /// </summary>
        public static string No_items_were_found_tip {
            get {
                return ResourceManager.GetString("No_items_were_found_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No members were found.
        /// </summary>
        public static string No_members_were_found {
            get {
                return ResourceManager.GetString("No_members_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to type a member name, e-mail or a member qualification.
        /// </summary>
        public static string No_members_were_found_tooltip {
            get {
                return ResourceManager.GetString("No_members_were_found_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no tasks.
        /// </summary>
        public static string no_tasks {
            get {
                return ResourceManager.GetString("no_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not belong to any organization team right now..
        /// </summary>
        public static string No_team_tooltip {
            get {
                return ResourceManager.GetString("No_team_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trophies for you.
        /// </summary>
        public static string no_trophies_for_you {
            get {
                return ResourceManager.GetString("no_trophies_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tasks done.
        /// </summary>
        public static string NormalTasks_Done {
            get {
                return ResourceManager.GetString("NormalTasks_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not assigned yet.
        /// </summary>
        public static string not_assigned_yet {
            get {
                return ResourceManager.GetString("not_assigned_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting engaging....
        /// </summary>
        public static string not_engaged {
            get {
                return ResourceManager.GetString("not_engaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only active.
        /// </summary>
        public static string only_active {
            get {
                return ResourceManager.GetString("only_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending engagements.
        /// </summary>
        public static string Pending_memberships {
            get {
                return ResourceManager.GetString("Pending_memberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project end.
        /// </summary>
        public static string PProject_end {
            get {
                return ResourceManager.GetString("PProject_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail account has not been informed yet.
        ///Please provide some informaton about your self, it will help other people to find you..
        /// </summary>
        public static string Profile_not_completed {
            get {
                return ResourceManager.GetString("Profile_not_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project start.
        /// </summary>
        public static string Project_start {
            get {
                return ResourceManager.GetString("Project_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent projects.
        /// </summary>
        public static string Recent_projects {
            get {
                return ResourceManager.GetString("Recent_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse.
        /// </summary>
        public static string Refuse {
            get {
                return ResourceManager.GetString("Refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Gravatar.
        /// </summary>
        public static string Remove_Image {
            get {
                return ResourceManager.GetString("Remove_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string Role_name {
            get {
                return ResourceManager.GetString("Role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string Role_short_name {
            get {
                return ResourceManager.GetString("Role_short_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name or skill.
        /// </summary>
        public static string Search_tooltip {
            get {
                return ResourceManager.GetString("Search_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (showing up to 25 team members).
        /// </summary>
        public static string showing_up_to_25_members {
            get {
                return ResourceManager.GetString("showing_up_to_25_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint {0} start.
        /// </summary>
        public static string Sprint_N_start {
            get {
                return ResourceManager.GetString("Sprint_N_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start a new project.
        /// </summary>
        public static string start_a_new_project {
            get {
                return ResourceManager.GetString("start_a_new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team code.
        /// </summary>
        public static string Team_code {
            get {
                return ResourceManager.GetString("Team_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to &apos;{0}&apos; ends.
        /// </summary>
        public static string to_end_project_N {
            get {
                return ResourceManager.GetString("to_end_project_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until &apos;{0}&apos; starts.
        /// </summary>
        public static string to_start_project_N {
            get {
                return ResourceManager.GetString("to_start_project_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to &apos;{0}&apos; sprint ends.
        /// </summary>
        public static string to_start_sprint_N {
            get {
                return ResourceManager.GetString("to_start_sprint_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today tasks.
        /// </summary>
        public static string Today_tasks {
            get {
                return ResourceManager.GetString("Today_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophies.
        /// </summary>
        public static string Trophies {
            get {
                return ResourceManager.GetString("Trophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view my team tasks.
        /// </summary>
        public static string view_my_team_tasks {
            get {
                return ResourceManager.GetString("view_my_team_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} total worked hours.
        /// </summary>
        public static string Worked_hours {
            get {
                return ResourceManager.GetString("Worked_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working with.
        /// </summary>
        public static string Working_with {
            get {
                return ResourceManager.GetString("Working_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload.
        /// </summary>
        public static string Workload {
            get {
                return ResourceManager.GetString("Workload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You belong to the &apos;{0}&apos; organization team..
        /// </summary>
        public static string Your_team_tooltip {
            get {
                return ResourceManager.GetString("Your_team_tooltip", resourceCulture);
            }
        }
    }
}
