//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumFactory.Team.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TROPHY_BUG_KILLER_DATE {
            get {
                return ((global::System.DateTime)(this["TROPHY_BUG_KILLER_DATE"]));
            }
            set {
                this["TROPHY_BUG_KILLER_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TROPHY_HARD_WORKER_DATE {
            get {
                return ((global::System.DateTime)(this["TROPHY_HARD_WORKER_DATE"]));
            }
            set {
                this["TROPHY_HARD_WORKER_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TROPHY_IMPROVER_DATE {
            get {
                return ((global::System.DateTime)(this["TROPHY_IMPROVER_DATE"]));
            }
            set {
                this["TROPHY_IMPROVER_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TROPHY_THE_FLASH_DATE {
            get {
                return ((global::System.DateTime)(this["TROPHY_THE_FLASH_DATE"]));
            }
            set {
                this["TROPHY_THE_FLASH_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TROPHY_EXPERT_DATE {
            get {
                return ((global::System.DateTime)(this["TROPHY_EXPERT_DATE"]));
            }
            set {
                this["TROPHY_EXPERT_DATE"] = value;
            }
        }
    }
}
